## IsTheWorldReadyForTheNextPandemic - Mini Project
### Project handled by Liza, Ravit, Hagit and Hodaya

**This notebook includes running of a comprehensive Exploratory Data Analysis (EDA) on base dataSet ready for modeling.**

---
## Part 1 · Setup, data

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [ ]:
# Core imports.
import numpy as np
np.random.seed(42)  # For reproducibility
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

# Set the path where your DataSet CSVs located.
data_dir = '/content/drive/MyDrive/DS_IsTheWorldReadyForTheNextPandemic/DATASET TO USE/'

## Re-arrainging the data in file "WHO-COVID-19-global-daily-data_md.csv":
1. Turning file "WHO-COVID-19-global-daily-data_md.csv" from date driven to year driven to alighn values
2. Print file EDA

In [ ]:
import os
import pandas as pd

# =====================================================================
# 1. הגדרת נתיב הספרייה ושם הקובץ (עדכנו את ה-PATH שלכן כאן)
# =====================================================================
FOLDER_PATH = '/content/drive/MyDrive/DS_IsTheWorldReadyForTheNextPandemic/DATASET TO USE/'  # הכניסו כאן את ה-PATH של הספרייה
FILE_NAME = 'WHO-COVID-19-global-daily-data_md.csv'         # שם הקובץ שלכן

# חיבור אוטומטי של הספרייה והקובץ לנתיב מלא אחד
FULL_PATH = os.path.join(FOLDER_PATH, FILE_NAME)

print(f"טוען את הקובץ מתוך הנתיב: {FULL_PATH}")

# =====================================================================
# 2. טעינת הקובץ וניקוי ראשוני
# =====================================================================
df = pd.read_csv(FULL_PATH)

# ניקוי רווחים מיותרים משמות העמודות ליתר ביטחון
df.columns = df.columns.str.strip()

# הפיכת עמודת התאריך לפורמט מתאים וחילוץ השנה לקבוצה
df['Date_reported'] = pd.to_datetime(df['Date_reported'], errors='coerce')
df['YEAR'] = df['Date_reported'].dt.year

# =====================================================================
# 3. הגדרת חוקי הקיבוץ (Aggregation Rules)
# =====================================================================
aggregation_rules = {
    'Country_code': 'first',      # שמירת קוד המדינה
    'WHO_region': 'first',        # שמירת האזור הגיאוגרפי
    'New_cases': 'sum',           # סכימת המקרים החדשים לאורך כל השנה
    'New_deaths': 'sum',          # סכימת מקרי המוות החדשים לאורך כל השנה
    'Cumulative_cases': 'max',    # הערך המקסימלי בשנה (סך הכל בסוף השנה)
    'Cumulative_deaths': 'max'    # הערך המקסימלי בשנה (סך הכל בסוף השנה)
}

# =====================================================================
# 4. ביצוע הקיבוץ ושמירת הקובץ השנתי באותה ספרייה
# =====================================================================
df_yearly = df.groupby(['Country', 'YEAR']).agg(aggregation_rules).reset_index()

# שמירת הקובץ החדש באותה הספרייה שהגדרתן למעלה
OUTPUT_NAME = 'yearly_covid_summary.csv'
OUTPUT_PATH = os.path.join(FOLDER_PATH, OUTPUT_NAME)
df_yearly.to_csv(OUTPUT_PATH, index=False)

print(f"הטבלה קובצה בהצלחה מרמה יומית לרמה שנתית!")
print(f"הקובץ המעובד נשמר בספרייה שלכן תחת השם: {OUTPUT_NAME}")
print(f"מימדי הטבלה החדשה: {df_yearly.shape}")

טוען את הקובץ מתוך הנתיב: /content/drive/MyDrive/DS_IsTheWorldReadyForTheNextPandemic/DATASET TO USE/WHO-COVID-19-global-daily-data_md.csv
הטבלה קובצה בהצלחה מרמה יומית לרמה שנתית!
הקובץ המעובד נשמר בספרייה שלכן תחת השם: yearly_covid_summary.csv
מימדי הטבלה החדשה: (1680, 8)

In [ ]:
# הדפסת 5 השורות הראשונות של הטבלה השנתית המקובצת
print("--- 5 השורות הראשונות בטבלה ---")
display(df_yearly.head(5))

# הדפסת 10 השורות הראשונות של הטבלה השנתית המקובצת
print("\n--- 10 השורות הראשונות בטבלה ---")
display(df_yearly.head(10))

--- 5 השורות הראשונות בטבלה ---

,Country,YEAR,Country_code,WHO_region,New_cases,New_deaths,Cumulative_cases,Cumulative_deaths
0,Afghanistan,2020.0,AF,EMR,20169.0,834.0,48826,1949
1,Afghanistan,2021.0,AF,EMR,44842.0,2095.0,157611,7325
2,Afghanistan,2022.0,AF,EMR,22594.0,203.0,206603,7839
3,Afghanistan,2023.0,AF,EMR,9772.0,55.0,229703,7965
4,Afghanistan,2024.0,AF,EMR,2115.0,7.0,235214,7998

--- 10 השורות הראשונות בטבלה ---

,Country,YEAR,Country_code,WHO_region,New_cases,New_deaths,Cumulative_cases,Cumulative_deaths
0,Afghanistan,2020.0,AF,EMR,20169.0,834.0,48826,1949
1,Afghanistan,2021.0,AF,EMR,44842.0,2095.0,157611,7325
2,Afghanistan,2022.0,AF,EMR,22594.0,203.0,206603,7839
3,Afghanistan,2023.0,AF,EMR,9772.0,55.0,229703,7965
4,Afghanistan,2024.0,AF,EMR,2115.0,7.0,235214,7998
5,Afghanistan,2025.0,AF,EMR,0.0,0.0,235214,7998
6,Afghanistan,2026.0,AF,EMR,0.0,0.0,235214,7998
7,Albania,2020.0,AL,EUR,20552.0,439.0,46061,965
8,Albania,2021.0,AL,EUR,61183.0,826.0,203215,3130
9,Albania,2022.0,AL,EUR,45213.0,164.0,332419,3594

In [ ]:
# 1. מדדים סטטיסטיים כלליים (ממוצע, חציון, סטיית תקן, מינימום ומקסימום)
print("--- מדדי מרכז ופיזור עבור העמודות המספריות ---")
# הוספנו .T (טרנספוזיציה) כדי להפוך את הטבלה, מה שיוצר תצוגה הרבה יותר נוחה לקריאה
display(df_yearly.describe().T)

# 2. בדיקת כמות הערכים החסרים (NaN) בכל עמודה
print("\n--- בדיקת ערכים חסרים (Missing Values) בכל עמודה ---")
missing_data = pd.DataFrame({
    'ערכים חסרים (כמות)': df_yearly.isnull().sum(),
    'ערכים חסרים (אחוז)': (df_yearly.isnull().sum() / len(df_yearly)) * 100
})
display(missing_data)

# 3. מדדים ספציפיים נוספים (מדדי גבנוניות וצידוד - Skewness & Kurtosis)
# מדדים אלו חשובים מאוד כדי לדעת אם התפלגות המשתנים שלכן נורמלית או מוטה
print("\n--- מדדי התפלגות מורחבים ---")
extended_stats = pd.DataFrame({
    'Skewness (צידוד)': df_yearly.select_dtypes(include=['number']).skew(),
    'Kurtosis (גבנוניות)': df_yearly.select_dtypes(include=['number']).kurt()
})
display(extended_stats)

--- מדדי מרכז ופיזור עבור העמודות המספריות ---

,count,mean,std,min,25%,50%,75%,max
YEAR,1680.0,2.023000e+03,2.000596e+00,2020.0,2021.0,2023.0,2025.00,2026.0
New_cases,1680.0,1.685526e+05,9.981113e+05,-134.0,0.0,617.5,17812.00,19193158.0
New_deaths,1680.0,1.678329e+03,9.888654e+03,-29.0,0.0,2.0,135.25,187497.0
Cumulative_cases,1680.0,2.437814e+06,9.383810e+06,0.0,13198.5,94909.0,994051.75,103436829.0
Cumulative_deaths,1680.0,2.501875e+04,9.480923e+04,0.0,114.5,1104.0,9940.50,1238189.0

--- בדיקת ערכים חסרים (Missing Values) בכל עמודה ---

                   ערכים חסרים (כמות)  ערכים חסרים (אחוז)
Country                             0            0.000000
YEAR                                0            0.000000
Country_code                        7            0.416667
WHO_region                          0            0.000000
New_cases                           0            0.000000
New_deaths                          0            0.000000
Cumulative_cases                    0            0.000000
Cumulative_deaths                   0            0.000000

--- מדדי התפלגות מורחבים ---

                   Skewness (צידוד)  Kurtosis (גבנוניות)
YEAR                       0.000000            -1.250148
New_cases                 11.077382           148.871987
New_deaths                12.004256           176.116916
Cumulative_cases           7.459067            67.379186
Cumulative_deaths          8.013562            80.011100

## Re-arrainging the data in file "epidemiology_Ind_md.csv":
1. Turning file "epidemiology_Ind_md.csv" from date driven to year driven to alighn values
2. Eliminating "Subregion" fields
3. Assign Null fields = 0
4. Print file EDA

In [ ]:
import os
import pandas as pd

# =====================================================================
# 1. הגדרת נתיב הספרייה ושם הקובץ האפידמיולוגי
# =====================================================================
FOLDER_PATH = '/content/drive/MyDrive/DS_IsTheWorldReadyForTheNextPandemic/DATASET TO USE/'  # עדכנו את ה-PATH שלכן כאן
FILE_NAME = 'epidemiology_Ind_md.csv'

FULL_PATH = os.path.join(FOLDER_PATH, FILE_NAME)
print(f"טוען את הקובץ מתוך: {FULL_PATH}")

# טעינת הקובץ וניקוי רווחים משמות העמודות
df = pd.read_csv(FULL_PATH)
df.columns = df.columns.str.strip()

# =====================================================================
# 2. הסרת עמודות D, E, F, G (לפי אינדקס המיקום שלהן בטבלה)
# =====================================================================
# עמודות D, E, F, G הן עמודות מספר 3, 4, 5, 6 (מתחילים לספור מ-0)
# אלו הן העמודות: subregion1_code, subregion1_name, subregion2_code, subregion2_name
columns_to_drop = [df.columns[3], df.columns[4], df.columns[5], df.columns[6]]
df = df.drop(columns=columns_to_drop)

# =====================================================================
# 3. טיפול בערכים חסרים: החלפת כל ה-NULL / NaN ב-0
# =====================================================================
df = df.fillna(0)

# חילוץ השנה מתוך עמודת התאריך לטובת הקיבוץ
df['date'] = pd.to_datetime(df['date'], errors='coerce')
df['YEAR'] = df['date'].dt.year

# =====================================================================
# 4. הגדרת חוקי הקיבוץ השנתי (Aggregation Rules)
# =====================================================================
# אגרגציה לפי לוגיקה של למידת מכונה: נתונים יומיים נסכום, נתונים מצטברים ניקח מקסימום
aggregation_rules = {
    'country_code': 'first',
    'country_name': 'first',
    'aggregation_level': 'first',
    'new_confirmed': 'sum',
    'new_deceased': 'sum',
    'new_recovered': 'sum',
    'new_tested': 'sum',
    'cumulative_confirmed': 'max',
    'cumulative_deceased': 'max',
    'cumulative_recovered': 'max',
    'cumulative_tested': 'max'
}

# =====================================================================
# 5. ביצוע הקיבוץ השנתי ושמירת הקובץ החדש
# =====================================================================
# מקבצים לפי מפתח המדינה (location_key) והשנה (YEAR)
df_yearly = df.groupby(['location_key', 'YEAR']).agg(aggregation_rules).reset_index()

# שמירת הקובץ המעובד באותה ספרייה
OUTPUT_NAME = 'yearly_epidemiology_cleaned.csv'
OUTPUT_PATH = os.path.join(FOLDER_PATH, OUTPUT_NAME)
df_yearly.to_csv(OUTPUT_PATH, index=False)

print("\nהפעולות בוצעו בהצלחה!")
print(f"1. עמודות D,E,F,G הוסרו.")
print(f"2. כל ערכי ה-NULL הוחלפו ב-0.")
print(f"3. הנתונים קובצו לרמה שנתית ונשמרו בשם: {OUTPUT_NAME}")
print(f"מימדי הטבלה השנתית החדשה: {df_yearly.shape}")

טוען את הקובץ מתוך: /content/drive/MyDrive/DS_IsTheWorldReadyForTheNextPandemic/DATASET TO USE/epidemiology_Ind_md.csv

הפעולות בוצעו בהצלחה!
1. עמודות D,E,F,G הוסרו.
2. כל ערכי ה-NULL הוחלפו ב-0.
3. הנתונים קובצו לרמה שנתית ונשמרו בשם: yearly_epidemiology_cleaned.csv
מימדי הטבלה השנתית החדשה: (699, 13)

In [ ]:
# הדפסת 10 השורות הראשונות של הטבלה המעובדת
print("--- 10 השורות הראשונות בטבלה השנתית הנקייה ---")
display(df_yearly.head(10))

--- 10 השורות הראשונות בטבלה השנתית הנקייה ---

,location_key,YEAR,country_code,country_name,aggregation_level,new_confirmed,new_deceased,new_recovered,new_tested,cumulative_confirmed,cumulative_deceased,cumulative_recovered,cumulative_tested
0,0,2020,0,Namibia,0,24536.0,208.0,0.0,199795.0,24536.0,208.0,0.0,209155.0
1,0,2021,0,Namibia,0,124942.0,3447.0,0.0,599977.0,149478.0,3655.0,0.0,872058.0
2,0,2022,0,Namibia,0,17167.0,422.0,0.0,47299.0,166645.0,4077.0,0.0,1056045.0
3,AD,2020,AD,Andorra,0,8117.0,84.0,0.0,0.0,8117.0,84.0,0.0,124804.0
4,AD,2021,AD,Andorra,0,15623.0,56.0,0.0,0.0,23740.0,140.0,0.0,266810.0
5,AD,2022,AD,Andorra,0,22407.0,15.0,0.0,0.0,46147.0,155.0,0.0,300307.0
6,AE,2020,AE,United Arab Emirates,0,209678.0,671.0,0.0,21035504.0,209678.0,671.0,0.0,21035504.0
7,AE,2021,AE,United Arab Emirates,0,554815.0,1494.0,0.0,91095231.0,764493.0,2165.0,0.0,112130735.0
8,AE,2022,AE,United Arab Emirates,0,256698.0,177.0,0.0,56391937.0,1021191.0,2342.0,0.0,168522672.0
9,AF,2020,AF,Afghanistan,0,52586.0,2211.0,0.0,0.0,52586.0,2211.0,0.0,0.0

In [ ]:
# 1. מדדים סטטיסטיים כלליים (ממוצע, חציון, סטיית תקן, מינימום ומקסימום)
print("--- מדדי מרכז ופיזור עבור העמודות המספריות ---")
# הוספנו .T (טרנספוזיציה) כדי להפוך את הטבלה, מה שיוצר תצוגה הרבה יותר נוחה לקריאה
display(df_yearly.describe().T)

# 2. בדיקת כמות הערכים החסרים (NaN) בכל עמודה
print("\n--- בדיקת ערכים חסרים (Missing Values) בכל עמודה ---")
missing_data = pd.DataFrame({
    'ערכים חסרים (כמות)': df_yearly.isnull().sum(),
    'ערכים חסרים (אחוז)': (df_yearly.isnull().sum() / len(df_yearly)) * 100
})
display(missing_data)

# 3. מדדים ספציפיים נוספים (מדדי גבנוניות וצידוד - Skewness & Kurtosis)
# מדדים אלו חשובים מאוד כדי לדעת אם התפלגות המשתנים שלכן נורמלית או מוטה
print("\n--- מדדי התפלגות מורחבים ---")
extended_stats = pd.DataFrame({
    'Skewness (צידוד)': df_yearly.select_dtypes(include=['number']).skew(),
    'Kurtosis (גבנוניות)': df_yearly.select_dtypes(include=['number']).kurt()
})
display(extended_stats)

--- מדדי מרכז ופיזור עבור העמודות המספריות ---

,count,mean,std,min,25%,50%,75%,max
YEAR,699.0,2.020996e+03,8.231841e-01,2019.0,2020.0,2021.0,2022.0,2.022000e+03
aggregation_level,699.0,0.000000e+00,0.000000e+00,0.0,0.0,0.0,0.0,0.000000e+00
new_confirmed,699.0,8.704470e+05,3.261539e+06,0.0,5565.5,39515.0,344716.0,3.878153e+07
new_deceased,699.0,9.243976e+03,3.627533e+04,0.0,36.0,354.0,3426.5,4.379340e+05
new_recovered,699.0,4.678906e+05,5.919337e+06,-252396.0,0.0,0.0,0.0,1.306439e+08
new_tested,699.0,7.241731e+06,3.503783e+07,0.0,0.0,15769.0,1782367.0,4.958196e+08
cumulative_confirmed,699.0,1.388567e+06,5.684010e+06,0.0,8273.0,71815.0,553250.0,9.244050e+07
cumulative_deceased,699.0,1.938976e+04,7.493490e+04,0.0,86.5,884.0,7659.0,1.005195e+06
cumulative_recovered,699.0,8.332587e+05,1.085335e+07,0.0,0.0,0.0,0.0,2.345841e+08
cumulative_tested,699.0,2.906669e+07,3.552377e+08,0.0,0.0,323516.0,4761611.5,9.214000e+09

--- בדיקת ערכים חסרים (Missing Values) בכל עמודה ---

                      ערכים חסרים (כמות)  ערכים חסרים (אחוז)
location_key                           0                 0.0
YEAR                                   0                 0.0
country_code                           0                 0.0
country_name                           0                 0.0
aggregation_level                      0                 0.0
new_confirmed                          0                 0.0
new_deceased                           0                 0.0
new_recovered                          0                 0.0
new_tested                             0                 0.0
cumulative_confirmed                   0                 0.0
cumulative_deceased                    0                 0.0
cumulative_recovered                   0                 0.0
cumulative_tested                      0                 0.0

--- מדדי התפלגות מורחבים ---

                      Skewness (צידוד)  Kurtosis (גבנוניות)
YEAR                         -0.022950            -1.449548
aggregation_level             0.000000             0.000000
new_confirmed                 7.015549            58.791811
new_deceased                  7.940472            75.235810
new_recovered                18.689066           378.205830
new_tested                    9.702955           112.989195
cumulative_confirmed          9.287799           115.218584
cumulative_deceased           8.015492            78.878115
cumulative_recovered         18.676884           369.349518
cumulative_tested            24.903037           642.943533

## Re-arrainging the data in file "vaccinations_Ind_md.csv":
Re-arrainging the data in file "vaccinations_Ind_md.csv":
1. Turning file "vaccinations_Ind_md.csv" from date driven to year driven to alighn values
2. Eliminating "Subregion" fields
3. Assign Null fields = 0
4. Print file EDA
##

In [ ]:
import os
import pandas as pd

# =====================================================================
# 1. הגדרת נתיב הספרייה ושם קובץ החיסונים
# =====================================================================
FOLDER_PATH = '/content/drive/MyDrive/DS_IsTheWorldReadyForTheNextPandemic/DATASET TO USE/'  # עדכנו את ה-PATH שלכן כאן
FILE_NAME = 'vaccinations_Ind_md.csv'

FULL_PATH = os.path.join(FOLDER_PATH, FILE_NAME)
print(f"טוען את קובץ החיסונים מתוך: {FULL_PATH}")

# טעינת הקובץ וניקוי רווחים משמות העמודות
df_vac = pd.read_csv(FULL_PATH)
df_vac.columns = df_vac.columns.str.strip()

# =====================================================================
# 2. הסרת עמודות D, E, F, G (לפי מיקום העמודה בטבלה)
# =====================================================================
# עמודות 3, 4, 5, 6 הן עמודות ה-subregion הריקות שרואים בתמונה
columns_to_drop = [df_vac.columns[3], df_vac.columns[4], df_vac.columns[5], df_vac.columns[6]]
df_vac = df_vac.drop(columns=columns_to_drop)

# =====================================================================
# 3. מילוי כל השדות הריקים (Null/NaN) ב-0
# =====================================================================
df_vac = df_vac.fillna(0)

# חילוץ השנה מתוך עמודת התאריך לטובת הקיבוץ השנתי
df_vac['date'] = pd.to_datetime(df_vac['date'], errors='coerce')
df_vac['YEAR'] = df_vac['date'].dt.year

# =====================================================================
# 4. בנייה אוטומטית של חוקי הקיבוץ (Aggregation Rules)
# =====================================================================
aggregation_rules = {
    'country_code': 'first',
    'country_name': 'first',
    'aggregation_level': 'first'
}

# סריקה אוטומטית של שאר העמודות בקובץ כדי להתאים sum או max
for col in df_vac.columns:
    if col in ['location_key', 'date', 'YEAR', 'country_code', 'country_name', 'aggregation_level']:
        continue

    # אם העמודה מייצגת נתון מצטבר, ניקח את הערך המקסימלי השנתי
    if 'cumulative' in col.lower() or 'total' in col.lower():
        aggregation_rules[col] = 'max'
    # אם העמודה מייצגת נתון יומי חדש, נסכום את כל השנה
    else:
        aggregation_rules[col] = 'sum'

# =====================================================================
# 5. ביצוע הקיבוץ (Groupby) ושמירת הקובץ השנתי המעובד
# =====================================================================
df_vac_yearly = df_vac.groupby(['location_key', 'YEAR']).agg(aggregation_rules).reset_index()

# שמירת הקובץ המעובד באותה ספרייה
OUTPUT_NAME = 'yearly_vaccinations_final_summary.csv'
OUTPUT_PATH = os.path.join(FOLDER_PATH, OUTPUT_NAME)
df_vac_yearly.to_csv(OUTPUT_PATH, index=False)

print("\n--- קובץ החיסונים עובד בהצלחה בהתאם לכל הדרישות! ---")
print(f"1. עמודות ה-subregion (D,E,F,G) הוסרו בהצלחה.")
print(f"2. כל השדות הריקים מולאו ב-0.")
print(f"3. עמודות מסוג Cumulative/Total קיבלו ערך מקסימלי, ועמודות מסוג New נסכמו שנתית.")
print(f"4. הקובץ השנתי נשמר בשם: {OUTPUT_NAME}")
print(f"מימדי הטבלה החדשה: {df_vac_yearly.shape}")

טוען את קובץ החיסונים מתוך: /content/drive/MyDrive/DS_IsTheWorldReadyForTheNextPandemic/DATASET TO USE/vaccinations_Ind_md.csv

--- קובץ החיסונים עובד בהצלחה בהתאם לכל הדרישות! ---
1. עמודות ה-subregion (D,E,F,G) הוסרו בהצלחה.
2. כל השדות הריקים מולאו ב-0.
3. עמודות מסוג Cumulative/Total קיבלו ערך מקסימלי, ועמודות מסוג New נסכמו שנתית.
4. הקובץ השנתי נשמר בשם: yearly_vaccinations_final_summary.csv
מימדי הטבלה החדשה: (476, 35)

In [ ]:
# הדפסת 10 השורות הראשונות של טבלת החיסונים המעובדת
print("--- 10 השורות הראשונות בטבלת החיסונים השנתית ---")
display(df_vac_yearly.head(10))

--- 10 השורות הראשונות בטבלת החיסונים השנתית ---

,location_key,YEAR,country_code,country_name,aggregation_level,new_persons_vaccinated,cumulative_persons_vaccinated,new_persons_fully_vaccinated,cumulative_persons_fully_vaccinated,new_vaccine_doses_administered,...,new_persons_fully_vaccinated_janssen,cumulative_persons_fully_vaccinated_janssen,new_vaccine_doses_administered_janssen,cumulative_vaccine_doses_administered_janssen,new_persons_vaccinated_sinovac,total_persons_vaccinated_sinovac,new_persons_fully_vaccinated_sinovac,total_persons_fully_vaccinated_sinovac,new_vaccine_doses_administered_sinovac,total_vaccine_doses_administered_sinovac
0,0,2021,0,Namibia,0,346454.0,346454.0,283630.0,283758.0,630212.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,0,2022,0,Namibia,0,240198.0,586652.0,230397.0,514155.0,317061.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,AD,2021,AD,Andorra,0,56509.0,57085.0,50220.0,51392.0,116670.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,AD,2022,AD,Andorra,0,808.0,57893.0,2086.0,53478.0,36949.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,AE,2021,AE,United Arab Emirates,0,9044888.0,9881456.0,8809559.0,9059559.0,21580283.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
5,AE,2022,AE,United Arab Emirates,0,109633.0,9991089.0,732707.0,9792266.0,2515470.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
6,AF,2021,AF,Afghanistan,0,4142857.0,4142857.0,3697600.0,3753224.0,4674518.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
7,AF,2022,AF,Afghanistan,0,6684327.0,10827184.0,6352276.0,10105500.0,7060117.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
8,AG,2021,AG,Antigua and Barbuda,0,62283.0,62283.0,56282.0,58863.0,121146.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
9,AG,2022,AG,Antigua and Barbuda,0,1808.0,64091.0,3168.0,62031.0,7121.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [ ]:
# 1. מדדי מרכז ופיזור (ממוצע, חציון, סטיית תקן, מינימום, מקסימום ואחוזונים)
print("--- מדדי מרכז ופיזור עבור עמודות החיסונים והתגובה ---")
# שימוש ב-.T הופך את הטבלה כדי שיהיה קל לקרוא את המדדים עבור עמודות החיסונים הארוכות
display(df_vac_yearly.describe().T)

# 2. וידאו סופי שאין יותר ערכים חסרים (התוצאה בכל העמודות צריכה להיות 0)
print("\n--- בדיקת ערכים חסרים (Missing Values) בקובץ החיסונים המעובד ---")
missing_summary = pd.DataFrame({
    'כמות ערכי NULL': df_vac_yearly.isnull().sum(),
    'אחוז ערכי NULL': (df_vac_yearly.isnull().sum() / len(df_vac_yearly)) * 100
})
display(missing_summary)

# 3. מדדי התפלגות (צידוד וגבנוניות - Skewness & Kurtosis)
print("\n--- מדדי התפלגות מורחבים של עמודות החיסונים ---")
distribution_stats = pd.DataFrame({
    'Skewness (צידוד)': df_vac_yearly.select_dtypes(include=['number']).skew(),
    'Kurtosis (גבנוניות)': df_vac_yearly.select_dtypes(include=['number']).kurt()
})
display(distribution_stats)

--- מדדי מרכז ופיזור עבור עמודות החיסונים והתגובה ---

,count,mean,std,min,25%,50%,75%,max
YEAR,476.0,2.021363e+03,6.392824e-01,2020.0,2021.00,2021.0,2022.00,2.022000e+03
aggregation_level,476.0,0.000000e+00,0.000000e+00,0.0,0.00,0.0,0.00,0.000000e+00
new_persons_vaccinated,476.0,9.945423e+06,5.263834e+07,0.0,32906.25,451097.5,3883015.00,8.456406e+08
cumulative_persons_vaccinated,476.0,2.083944e+07,1.057700e+08,0.0,103866.50,1483235.0,7724095.50,1.302773e+09
new_persons_fully_vaccinated,476.0,8.683196e+06,4.090723e+07,0.0,26861.25,390165.5,3213335.00,6.032172e+08
cumulative_persons_fully_vaccinated,476.0,1.846165e+07,9.758260e+07,0.0,71961.50,1223977.5,6478352.50,1.270656e+09
new_vaccine_doses_administered,476.0,2.609079e+07,1.561657e+08,0.0,111497.00,1350678.5,9711720.25,2.836769e+09
cumulative_vaccine_doses_administered,476.0,4.517727e+07,2.420416e+08,0.0,216357.00,2720911.0,16557428.50,3.434774e+09
new_persons_vaccinated_pfizer,476.0,3.279328e+04,6.313132e+05,0.0,0.00,0.0,0.00,1.363560e+07
cumulative_persons_vaccinated_pfizer,476.0,6.143949e+04,9.490076e+05,0.0,0.00,0.0,0.00,1.560960e+07
new_persons_fully_vaccinated_pfizer,476.0,2.681546e+05,4.626804e+06,0.0,0.00,0.0,0.00,9.921628e+07
cumulative_persons_fully_vaccinated_pfizer,476.0,5.752506e+05,8.002189e+06,0.0,0.00,0.0,0.00,1.292668e+08
new_vaccine_doses_administered_pfizer,476.0,6.632286e+05,1.181012e+07,0.0,0.00,0.0,0.00,2.490339e+08
cumulative_vaccine_doses_administered_pfizer,476.0,1.383150e+06,2.142517e+07,0.0,0.00,0.0,0.00,3.625211e+08
new_persons_vaccinated_moderna,476.0,0.000000e+00,0.000000e+00,0.0,0.00,0.0,0.00,0.000000e+00
cumulative_persons_vaccinated_moderna,476.0,0.000000e+00,0.000000e+00,0.0,0.00,0.0,0.00,0.000000e+00
new_persons_fully_vaccinated_moderna,476.0,1.335508e+05,2.706194e+06,0.0,0.00,0.0,0.00,5.886424e+07
cumulative_persons_fully_vaccinated_moderna,476.0,3.180575e+05,4.903962e+06,0.0,0.00,0.0,0.00,7.805066e+07
new_vaccine_doses_administered_moderna,476.0,3.902367e+05,7.021065e+06,0.0,0.00,0.0,0.00,1.487143e+08
cumulative_vaccine_doses_administered_moderna,476.0,8.914713e+05,1.379092e+07,0.0,0.00,0.0,0.00,2.306894e+08
new_persons_vaccinated_janssen,476.0,0.000000e+00,0.000000e+00,0.0,0.00,0.0,0.00,0.000000e+00
cumulative_persons_vaccinated_janssen,476.0,0.000000e+00,0.000000e+00,0.0,0.00,0.0,0.00,0.000000e+00
new_persons_fully_vaccinated_janssen,476.0,3.548767e+04,7.395818e+05,0.0,0.00,0.0,0.00,1.611886e+07
cumulative_persons_fully_vaccinated_janssen,476.0,7.022395e+04,1.082512e+06,0.0,0.00,0.0,0.00,1.709994e+07
new_vaccine_doses_administered_janssen,476.0,3.924306e+04,7.997817e+05,0.0,0.00,0.0,0.00,1.740526e+07
cumulative_vaccine_doses_administered_janssen,476.0,7.668515e+04,1.182518e+06,0.0,0.00,0.0,0.00,1.888829e+07
new_persons_vaccinated_sinovac,476.0,2.141657e+04,4.639330e+05,0.0,0.00,0.0,0.00,1.012172e+07
total_persons_vaccinated_sinovac,476.0,4.053634e+02,8.714513e+03,0.0,0.00,0.0,0.00,1.901130e+05
new_persons_fully_vaccinated_sinovac,476.0,0.000000e+00,0.000000e+00,0.0,0.00,0.0,0.00,0.000000e+00
total_persons_fully_vaccinated_sinovac,476.0,0.000000e+00,0.000000e+00,0.0,0.00,0.0,0.00,0.000000e+00
new_vaccine_doses_administered_sinovac,476.0,0.000000e+00,0.000000e+00,0.0,0.00,0.0,0.00,0.000000e+00
total_vaccine_doses_administered_sinovac,476.0,0.000000e+00,0.000000e+00,0.0,0.00,0.0,0.00,0.000000e+00

--- בדיקת ערכים חסרים (Missing Values) בקובץ החיסונים המעובד ---

                                               כמות ערכי NULL  אחוז ערכי NULL
location_key                                                0             0.0
YEAR                                                        0             0.0
country_code                                                0             0.0
country_name                                                0             0.0
aggregation_level                                           0             0.0
new_persons_vaccinated                                      0             0.0
cumulative_persons_vaccinated                               0             0.0
new_persons_fully_vaccinated                                0             0.0
cumulative_persons_fully_vaccinated                         0             0.0
new_vaccine_doses_administered                              0             0.0
cumulative_vaccine_doses_administered                       0             0.0
new_persons_vaccinated_pfizer                               0             0.0
cumulative_persons_vaccinated_pfizer                        0             0.0
new_persons_fully_vaccinated_pfizer                         0             0.0
cumulative_persons_fully_vaccinated_pfizer                  0             0.0
new_vaccine_doses_administered_pfizer                       0             0.0
cumulative_vaccine_doses_administered_pfizer                0             0.0
new_persons_vaccinated_moderna                              0             0.0
cumulative_persons_vaccinated_moderna                       0             0.0
new_persons_fully_vaccinated_moderna                        0             0.0
cumulative_persons_fully_vaccinated_moderna                 0             0.0
new_vaccine_doses_administered_moderna                      0             0.0
cumulative_vaccine_doses_administered_moderna               0             0.0
new_persons_vaccinated_janssen                              0             0.0
cumulative_persons_vaccinated_janssen                       0             0.0
new_persons_fully_vaccinated_janssen                        0             0.0
cumulative_persons_fully_vaccinated_janssen                 0             0.0
new_vaccine_doses_administered_janssen                      0             0.0
cumulative_vaccine_doses_administered_janssen               0             0.0
new_persons_vaccinated_sinovac                              0             0.0
total_persons_vaccinated_sinovac                            0             0.0
new_persons_fully_vaccinated_sinovac                        0             0.0
total_persons_fully_vaccinated_sinovac                      0             0.0
new_vaccine_doses_administered_sinovac                      0             0.0
total_vaccine_doses_administered_sinovac                    0             0.0

--- מדדי התפלגות מורחבים של עמודות החיסונים ---

,Skewness (צידוד),Kurtosis (גבנוניות)
YEAR,-0.497759,-0.666882
aggregation_level,0.000000,0.000000
new_persons_vaccinated,12.446357,176.984858
cumulative_persons_vaccinated,10.059624,108.544624
new_persons_fully_vaccinated,10.410430,127.385781
cumulative_persons_fully_vaccinated,10.624531,122.013276
new_vaccine_doses_administered,14.301468,236.785894
cumulative_vaccine_doses_administered,10.952690,131.856422
new_persons_vaccinated_pfizer,21.210113,456.714683
cumulative_persons_vaccinated_pfizer,15.483939,239.835687
new_persons_fully_vaccinated_pfizer,20.773445,443.214495
cumulative_persons_fully_vaccinated_pfizer,15.158441,231.906260
new_vaccine_doses_administered_pfizer,20.032873,416.099657
cumulative_vaccine_doses_administered_pfizer,15.613601,245.166967
new_persons_vaccinated_moderna,0.000000,0.000000
cumulative_persons_vaccinated_moderna,0.000000,0.000000
new_persons_fully_vaccinated_moderna,21.620023,469.950439
cumulative_persons_fully_vaccinated_moderna,15.400884,236.412810
new_vaccine_doses_administered_moderna,20.232946,423.209183
cumulative_vaccine_doses_administered_moderna,15.553974,242.717170
new_persons_vaccinated_janssen,0.000000,0.000000
cumulative_persons_vaccinated_janssen,0.000000,0.000000
new_persons_fully_vaccinated_janssen,21.744393,473.804419
cumulative_persons_fully_vaccinated_janssen,15.390841,235.998484
new_vaccine_doses_administered_janssen,21.650848,470.915179
cumulative_vaccine_doses_administered_janssen,15.406767,236.655459
new_persons_vaccinated_sinovac,21.815743,475.950750
total_persons_vaccinated_sinovac,21.810165,475.786278
new_persons_fully_vaccinated_sinovac,0.000000,0.000000
total_persons_fully_vaccinated_sinovac,0.000000,0.000000
new_vaccine_doses_administered_sinovac,0.000000,0.000000
total_vaccine_doses_administered_sinovac,0.000000,0.000000

## Re-arrainging the data in file "demographic_Ind_md.csv":
Re-arrainging the data in file "demographic_Ind_md.csv":
1. Eliminating "Subregion" fields
2. Assign Null fields = median
3. Print file EDA
##

In [ ]:
import os
import pandas as pd

# =====================================================================
# 1. הגדרת נתיב הספרייה ושם קובץ הדמוגרפיה (עם תיקון הסיומת)
# =====================================================================
FOLDER_PATH = '/content/drive/MyDrive/DS_IsTheWorldReadyForTheNextPandemic/DATASET TO USE/'
FILE_NAME = 'demographics_Ind_md.csv'

FULL_PATH = os.path.join(FOLDER_PATH, FILE_NAME)
print(f"טוען את קובץ הדמוגרפיה מתוך: {FULL_PATH}")

# טעינת הקובץ וניקוי רווחים משמות העמודות
df_new = pd.read_csv(FULL_PATH)
df_new.columns = df_new.columns.str.strip()

# =====================================================================
# 2. הסרת עמודות D, E, F, G (עמודות באינדקסים 3, 4, 5, 6)
# =====================================================================
# משיכת שמות העמודות המדויקים לפי המיקום שלהן בטבלה
columns_to_drop = [df_new.columns[3], df_new.columns[4], df_new.columns[5], df_new.columns[6]]
df_demo_cleaned = df_new.drop(columns=columns_to_drop)

# =====================================================================
# 3. מילוי כל השדות הריקים (Null / NaN) בחציון של כל עמודה
# =====================================================================
# המשתנה numeric_only=True מבטיח חישוב חציון רק לעמודות עם מספרים ומניעת שגיאות
column_medians = df_demo_cleaned.median(numeric_only=True)
df_demo_cleaned = df_demo_cleaned.fillna(column_medians)

# =====================================================================
# 4. שמירת קובץ הדמוגרפיה הנקי באותה ספרייה
# =====================================================================
OUTPUT_NAME = 'cleaned_demographics_final.csv'
OUTPUT_PATH = os.path.join(FOLDER_PATH, OUTPUT_NAME)
df_demo_cleaned.to_csv(OUTPUT_PATH, index=False)

print("\n--- הריצה הסתיימה בהצלחה! הקובץ נוקה ונשמר ---")
print(f"הקובץ הנקי נשמר בשם: {OUTPUT_NAME}")
print(f"מימדי הטבלה (שורות, עמודות): {df_demo_cleaned.shape}")

# =====================================================================
# 5. הדפסת 10 השורות הראשונות לבדיקה ויזואלית סופית
# =====================================================================
print("\n--- 10 השורות הראשונות בטבלת הדמוגרפיה הנקייה ---")
display(df_demo_cleaned.head(10))

טוען את קובץ הדמוגרפיה מתוך: /content/drive/MyDrive/DS_IsTheWorldReadyForTheNextPandemic/DATASET TO USE/demographics_Ind_md.csv

--- הריצה הסתיימה בהצלחה! הקובץ נוקה ונשמר ---
הקובץ הנקי נשמר בשם: cleaned_demographics_final.csv
מימדי הטבלה (שורות, עמודות): (246, 22)

--- 10 השורות הראשונות בטבלת הדמוגרפיה הנקייה ---

,location_key,country_code,country_name,aggregation_level,population,population_male,population_female,population_rural,population_urban,population_largest_city,...,human_development_index,population_age_00_09,population_age_10_19,population_age_20_29,population_age_30_39,population_age_40_49,population_age_50_59,population_age_60_69,population_age_70_79,population_age_80_and_older
0,AD,AD,Andorra,0,77265.0,58625.0,55581.0,9269.0,67873.0,2159137.0,...,0.858,9370.0,12022.0,10727.0,12394.0,21001.0,20720.0,14433.0,8657.0,4881.0
1,AE,AE,United Arab Emirates,0,9890400.0,6836349.0,3054051.0,1290785.0,8479744.0,2833079.0,...,0.863,1011713.0,842991.0,2149343.0,3169314.0,1608109.0,797913.0,242707.0,55884.0,12426.0
2,AF,AF,Afghanistan,0,38928341.0,19976265.0,18952076.0,28244481.0,9797273.0,4114030.0,...,0.498,11088732.0,9821559.0,7035871.0,4534646.0,2963459.0,1840198.0,1057496.0,480455.0,105925.0
3,AG,AG,Antigua and Barbuda,0,97928.0,47269.0,50659.0,73318.0,23800.0,2159137.0,...,0.780,14583.0,13867.0,14894.0,14094.0,13860.0,12832.0,8043.0,4101.0,1654.0
4,AI,AI,Anguilla,0,15002.0,7151.0,7971.0,1758851.0,3850231.0,2159137.0,...,0.735,2196.0,2146.0,2005.0,2081.0,2187.0,2214.0,1351.0,641.0,301.0
5,AL,AL,Albania,0,2862427.0,1429594.0,1432833.0,1106598.0,1747593.0,484624.0,...,0.764,319074.0,381542.0,474360.0,366807.0,339697.0,398271.0,315510.0,190753.0,52224.0
6,AM,AM,Armenia,0,2963234.0,1393747.0,1569487.0,1087883.0,1869848.0,1083323.0,...,0.743,418859.0,368930.0,408924.0,503953.0,353088.0,362653.0,328402.0,126743.0,91682.0
7,AN,AN,Netherlands Antilles,0,197041.0,2723290.0,2761414.0,1758851.0,3850231.0,2159137.0,...,0.735,773779.0,718837.0,824456.0,846180.0,686435.0,535459.0,348752.0,171250.0,52206.0
8,AO,AO,Angola,0,32866267.0,16260870.0,16605398.0,10764270.0,21061025.0,8044735.0,...,0.581,10899168.0,7881779.0,5306037.0,3699729.0,2412735.0,1464602.0,785897.0,331729.0,84592.0
9,AQ,AQ,Antarctica,0,4400.0,2723290.0,2761414.0,1758851.0,3850231.0,2159137.0,...,0.735,773779.0,718837.0,824456.0,846180.0,686435.0,535459.0,348752.0,171250.0,52206.0

In [ ]:
# 1. מדדי מרכז ופיזור (ממוצע, חציון, סטיית תקן, מינימום, מקסימום ואחוזונים)
print("--- מדדי מרכז ופיזור עבור נתוני האוכלוסייה והדמוגרפיה ---")
# שימוש ב-.T הופך את הטבלה כדי שיהיה קל לקרוא את המדדים עבור פלחי הגיל הרבים
display(df_demo_cleaned.describe().T)

# 2. וידאו סופי שאין יותר ערכים חסרים (התוצאה בכל העמודות צריכה להיות 0)
print("\n--- בדיקת ערכים חסרים (Missing Values) בקובץ הדמוגרפיה המעובד ---")
missing_summary = pd.DataFrame({
    'כמות ערכי NULL': df_demo_cleaned.isnull().sum(),
    'אחוז ערכי NULL': (df_demo_cleaned.isnull().sum() / len(df_demo_cleaned)) * 100
})
display(missing_summary)

# 3. מדדי התפלגות (צידוד וגבנוניות - Skewness & Kurtosis)
print("\n--- מדדי התפלגות מורחבים של עמודות הדמוגרפיה ---")
distribution_stats = pd.DataFrame({
    'Skewness (צידוד)': df_demo_cleaned.select_dtypes(include=['number']).skew(),
    'Kurtosis (גבנוניות)': df_demo_cleaned.select_dtypes(include=['number']).kurt()
})
display(distribution_stats)

--- מדדי מרכז ופיזור עבור נתוני האוכלוסייה והדמוגרפיה ---

,count,mean,std,min,25%,50%,75%,max
aggregation_level,246.0,0.000000e+00,0.000000e+00,0.000,0.000000e+00,0.000,0.000000e+00,0.000000e+00
population,246.0,3.156854e+07,1.321704e+08,0.000,2.859610e+05,5057677.000,1.904164e+07,1.439324e+09
population_male,246.0,1.602516e+07,6.798714e+07,292.000,2.830432e+05,2723290.000,9.353762e+06,7.382473e+08
population_female,246.0,1.575396e+07,6.415115e+07,262.000,2.505100e+05,2761414.000,9.687880e+06,7.010764e+08
population_rural,246.0,1.401731e+07,6.874687e+07,0.000,3.881455e+05,1758851.000,8.500004e+06,8.953862e+08
population_urban,246.0,1.781009e+07,6.677484e+07,5464.000,8.107615e+05,3850231.000,9.165077e+06,8.429340e+08
population_largest_city,246.0,3.595983e+06,4.856516e+06,342743.000,1.749503e+06,2159137.000,2.864050e+06,3.743519e+07
population_clustered,246.0,8.921366e+06,3.141167e+07,1026758.000,3.137690e+06,3137690.000,3.137690e+06,3.989761e+08
population_density,246.0,4.507490e+02,2.282569e+03,0.138,3.956600e+01,92.855,2.240168e+02,2.633826e+04
human_development_index,246.0,7.141057e-01,1.329299e-01,0.354,6.477500e-01,0.735,7.977500e-01,9.570000e-01
population_age_00_09,246.0,5.484006e+06,1.991802e+07,72.000,7.323175e+04,773779.000,3.969597e+06,2.348616e+08
population_age_10_19,246.0,5.120873e+06,2.028690e+07,81.000,6.613100e+04,718837.000,3.689561e+06,2.522015e+08
population_age_20_29,246.0,4.867140e+06,2.013061e+07,53.000,8.066425e+04,824456.000,3.119667e+06,2.399021e+08
population_age_30_39,246.0,4.695253e+06,2.067608e+07,75.000,8.223400e+04,846180.000,2.794580e+06,2.288304e+08
population_age_40_49,246.0,3.959031e+06,1.804476e+07,75.000,6.587600e+04,686435.000,2.048405e+06,2.161118e+08
population_age_50_59,246.0,3.385355e+06,1.678434e+07,100.000,5.038875e+04,535459.000,1.454160e+06,2.221859e+08
population_age_60_69,246.0,2.396953e+06,1.158729e+07,54.000,3.063525e+04,348752.000,1.080178e+06,1.516639e+08
population_age_70_79,246.0,1.261805e+06,5.595138e+06,17.000,1.391400e+04,171250.000,5.657192e+05,7.149430e+07
population_age_80_and_older,246.0,5.856110e+05,2.290069e+06,3.000,5.217250e+03,52206.000,2.607395e+05,2.661810e+07

--- בדיקת ערכים חסרים (Missing Values) בקובץ הדמוגרפיה המעובד ---

                             כמות ערכי NULL  אחוז ערכי NULL
location_key                              1        0.406504
country_code                              1        0.406504
country_name                              0        0.000000
aggregation_level                         0        0.000000
population                                0        0.000000
population_male                           0        0.000000
population_female                         0        0.000000
population_rural                          0        0.000000
population_urban                          0        0.000000
population_largest_city                   0        0.000000
population_clustered                      0        0.000000
population_density                        0        0.000000
human_development_index                   0        0.000000
population_age_00_09                      0        0.000000
population_age_10_19                      0        0.000000
population_age_20_29                      0        0.000000
population_age_30_39                      0        0.000000
population_age_40_49                      0        0.000000
population_age_50_59                      0        0.000000
population_age_60_69                      0        0.000000
population_age_70_79                      0        0.000000
population_age_80_and_older               0        0.000000

--- מדדי התפלגות מורחבים של עמודות הדמוגרפיה ---

                             Skewness (צידוד)  Kurtosis (גבנוניות)
aggregation_level                    0.000000             0.000000
population                           9.453553            96.325789
population_male                      9.546104            97.712348
population_female                    9.364928            95.005244
population_rural                    10.734929           126.075172
population_urban                     9.412471           104.510330
population_largest_city              3.685842            16.267316
population_clustered                 9.561684           106.196855
population_density                   9.615504            98.610494
human_development_index             -0.590846            -0.070601
population_age_00_09                 8.886358            90.940345
population_age_10_19                 9.663038           106.093531
population_age_20_29                 9.624024           101.815721
population_age_30_39                 9.695209           100.182658
population_age_40_49                 9.957714           106.778212
population_age_50_59                10.885815           130.681914
population_age_60_69                10.566203           124.563430
population_age_70_79                 9.810496           111.042067
population_age_80_and_older          7.992399            76.871610

## Re-arrainging the data in file "health_Demog_Ind_md.csv":
Re-arrainging the data in file "health_Demog_Ind_md.csv":
1. Eliminating "Subregion" fields
2. Assign Null fields = median
3. Print file EDA
##

In [ ]:
import os
import pandas as pd

# =====================================================================
# 1. הגדרת נתיב הספרייה ושם קובץ הבריאות והדמוגרפיה
# =====================================================================
FOLDER_PATH = '/content/drive/MyDrive/DS_IsTheWorldReadyForTheNextPandemic/DATASET TO USE/'
FILE_NAME = 'health_Demog_Ind_md.csv'  # שם הקובץ שביקשתן לנקות

FULL_PATH = os.path.join(FOLDER_PATH, FILE_NAME)
print(f"טוען את קובץ הבריאות והדמוגרפיה מתוך: {FULL_PATH}")

# טעינת הקובץ וניקוי רווחים מיותרים משמות העמודות
df_health_demo = pd.read_csv(FULL_PATH)
df_health_demo.columns = df_health_demo.columns.str.strip()

# =====================================================================
# 2. הסרת עמודות D, E, F, G (עמודות באינדקסים 3, 4, 5, 6)
# =====================================================================
# שמות העמודות subregion1_code, subregion1_name, subregion2_code, subregion2_name
columns_to_drop = [
    df_health_demo.columns[3],
    df_health_demo.columns[4],
    df_health_demo.columns[5],
    df_health_demo.columns[6]
]
df_health_demo_cleaned = df_health_demo.drop(columns=columns_to_drop)

# =====================================================================
# 3. מילוי כל השדות הריקים (Null / NaN) בחציון של כל עמודה
# =====================================================================
# numeric_only=True מבטיח חישוב חציון רק לעמודות מספריות ומונע שגיאות בעמודות טקסט
column_medians = df_health_demo_cleaned.median(numeric_only=True)
df_health_demo_cleaned = df_health_demo_cleaned.fillna(column_medians)

# =====================================================================
# 4. שמירת הקובץ הנקי החדש באותה ספרייה
# =====================================================================
OUTPUT_NAME = 'cleaned_health_demographics_final.csv'
OUTPUT_PATH = os.path.join(FOLDER_PATH, OUTPUT_NAME)
df_health_demo_cleaned.to_csv(OUTPUT_PATH, index=False)

print("\n--- הקובץ עובד ונוקה בהצלחה! ---")
print(f"1. עמודות D, E, F, G הוסרו מהטבלה.")
print(f"2. כל השדות הריקים מולאו בחציון של כל עמודה.")
print(f"3. הקובץ הנקי נשמר בשם: {OUTPUT_NAME}")
print(f"מימדי הטבלה החדשה (שורות, עמודות): {df_health_demo_cleaned.shape}")

# =====================================================================
# 5. הדפסת 10 השורות הראשונות לבדיקה ויזואלית סופית
# =====================================================================
print("\n--- 10 השורות הראשונות בטבלה הנקייה ---")
display(df_health_demo_cleaned.head(10))

טוען את קובץ הבריאות והדמוגרפיה מתוך: /content/drive/MyDrive/DS_IsTheWorldReadyForTheNextPandemic/DATASET TO USE/health_Demog_Ind_md.csv

--- הקובץ עובד ונוקה בהצלחה! ---
1. עמודות D, E, F, G הוסרו מהטבלה.
2. כל השדות הריקים מולאו בחציון של כל עמודה.
3. הקובץ הנקי נשמר בשם: cleaned_health_demographics_final.csv
מימדי הטבלה החדשה (שורות, עמודות): (210, 35)

--- 10 השורות הראשונות בטבלה הנקייה ---

,location_key,country_code,country_name,aggregation_level,population,population_male,population_female,population_rural,population_urban,population_largest_city,...,infant_mortality_rate,adult_male_mortality_rate,adult_female_mortality_rate,pollution_mortality_rate,comorbidity_mortality_rate,hospital_beds_per_1000,nurses_per_1000,physicians_per_1000,health_expenditure_usd,out_of_pocket_health_expenditure_usd
0,AD,AD,Andorra,0,77265.0,58625.0,55581.0,9269.0,67873.0,2159137.0,...,2.7,177.539,95.579,68.6,18.8,2.3,4.0128,3.3333,4040.786621,1688.121460
1,AE,AE,United Arab Emirates,0,9890400.0,6836349.0,3054051.0,1290785.0,8479744.0,2833079.0,...,6.5,69.555,44.863,54.7,16.8,2.3,5.7271,2.5278,1357.017456,256.034485
2,AF,AF,Afghanistan,0,38928341.0,19976265.0,18952076.0,28244481.0,9797273.0,4114030.0,...,47.9,237.554,192.532,211.1,29.8,0.5,0.1755,0.2782,67.122650,50.665913
3,AG,AG,Antigua and Barbuda,0,97928.0,47269.0,50659.0,73318.0,23800.0,2159137.0,...,5.0,126.917,83.136,29.9,22.6,2.3,4.5171,2.9560,673.859680,235.749039
4,AL,AL,Albania,0,2862427.0,1429594.0,1432833.0,1106598.0,1747593.0,484624.0,...,7.8,93.315,49.486,68.0,17.0,2.3,3.6495,1.2164,335.949448,92.757919
5,AM,AM,Armenia,0,2963234.0,1393747.0,1569487.0,1087883.0,1869848.0,1083323.0,...,11.0,173.428,65.595,54.8,22.3,4.2,6.1070,4.4023,407.635864,343.832977
6,AO,AO,Angola,0,32866267.0,16260870.0,16605398.0,10764270.0,21061025.0,8044735.0,...,51.6,327.044,220.291,118.5,16.5,2.3,0.4075,0.2146,114.459641,39.054794
7,AR,AR,Argentina,0,44938712.0,19523766.0,20593330.0,3599141.0,41339571.0,15057273.0,...,8.8,147.086,79.483,26.6,15.8,2.3,2.5996,3.9901,1324.603516,198.935944
8,AT,AT,Austria,0,8858775.0,4357033.0,4501742.0,3682651.0,5194416.0,1915338.0,...,2.9,79.032,41.779,15.3,11.4,2.3,7.0899,5.1697,4939.875488,948.617432
9,AU,AU,Australia,0,25499881.0,12698625.0,12801256.0,3519551.0,21844756.0,4870388.0,...,3.1,75.835,44.673,8.4,9.1,2.3,12.5508,3.6778,5331.817871,967.837036

In [ ]:
# 1. מדדי מרכז ופיזור (ממוצע, חציון, סטיית תקן, מינימום, מקסימום ואחוזונים)
print("--- מדדי מרכז ופיזור עבור נתוני הבריאות והחוסן הרפואי ---")
# שימוש ב-.T הופך את הטבלה כדי שתוכלו לקרוא בנוחות את המדדים עבור המשתנים הרבים (רופאים, מיטות וכו')
display(df_health_demo_cleaned.describe().T)

# 2. וידאו סופי שאין יותר ערכים חסרים (התוצאה בכל העמודות צריכה להיות 0)
print("\n--- בדיקת ערכים חסרים (Missing Values) בקובץ הבריאות המעובד ---")
missing_summary = pd.DataFrame({
    'כמות ערכי NULL': df_health_demo_cleaned.isnull().sum(),
    'אחוז ערכי NULL': (df_health_demo_cleaned.isnull().sum() / len(df_health_demo_cleaned)) * 100
})
display(missing_summary)

# 3. מדדי התפלגות (צידוד וגבנוניות - Skewness & Kurtosis)
print("\n--- מדדי התפלגות מורחבים של עמודות הבריאות ---")
distribution_stats = pd.DataFrame({
    'Skewness (צידוד)': df_health_demo_cleaned.select_dtypes(include=['number']).skew(),
    'Kurtosis (גבנוניות)': df_health_demo_cleaned.select_dtypes(include=['number']).kurt()
})
display(distribution_stats)

--- מדדי מרכז ופיזור עבור נתוני הבריאות והחוסן הרפואי ---

,count,mean,std,min,25%,50%,75%,max
aggregation_level,210.0,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00
population,210.0,3.681910e+07,1.424290e+08,1.083400e+04,1.031042e+06,6.981902e+06,2.622841e+07,1.439324e+09
population_male,210.0,1.856165e+07,7.330380e+07,4.785000e+03,5.318038e+05,3.437706e+06,1.313246e+07,7.382473e+08
population_female,210.0,1.824112e+07,6.914431e+07,5.460000e+03,4.992388e+05,3.478974e+06,1.314730e+07,7.010764e+08
population_rural,210.0,1.615311e+07,7.422149e+07,0.000000e+00,2.230962e+05,1.951483e+06,9.989382e+06,8.953862e+08
population_urban,210.0,2.027609e+07,7.200636e+07,5.464000e+03,5.759930e+05,3.924621e+06,1.111056e+07,8.429340e+08
population_largest_city,210.0,3.842299e+06,5.218409e+06,3.427430e+05,1.396078e+06,2.159137e+06,3.118484e+06,3.743519e+07
population_clustered,210.0,9.912853e+06,3.391018e+07,1.026758e+06,2.798384e+06,3.137690e+06,4.506963e+06,3.989761e+08
population_density,210.0,4.810649e+02,2.456898e+03,1.380000e-01,3.674375e+01,9.285500e+01,2.278038e+02,2.633826e+04
human_development_index,210.0,7.096857e-01,1.429539e-01,3.540000e-01,6.060000e-01,7.350000e-01,8.037500e-01,9.570000e-01
population_age_00_09,210.0,6.370003e+06,2.143918e+07,1.599000e+03,1.873808e+05,1.149490e+06,5.093570e+06,2.348616e+08
population_age_10_19,210.0,5.946808e+06,2.185703e+07,1.830000e+03,1.762030e+05,1.075799e+06,4.749457e+06,2.522015e+08
population_age_20_29,210.0,5.639847e+06,2.169985e+07,1.547000e+03,1.593175e+05,1.085789e+06,4.079183e+06,2.399021e+08
population_age_30_39,210.0,5.435483e+06,2.230023e+07,1.858000e+03,1.596025e+05,1.060004e+06,3.392608e+06,2.288304e+08
population_age_40_49,210.0,4.580803e+06,1.946717e+07,9.710000e+02,1.074452e+05,8.484760e+05,2.406516e+06,2.161118e+08
population_age_50_59,210.0,3.917584e+06,1.811706e+07,8.850000e+02,8.921400e+04,6.289050e+05,1.938580e+06,2.221859e+08
population_age_60_69,210.0,2.773040e+06,1.250503e+07,4.990000e+02,5.951375e+04,4.187135e+05,1.307254e+06,1.516639e+08
population_age_70_79,210.0,1.461122e+06,6.034455e+06,1.180000e+02,2.570625e+04,2.108400e+05,7.391898e+05,7.149430e+07
population_age_80_and_older,210.0,6.786521e+05,2.466753e+06,2.200000e+01,1.032075e+04,7.579050e+04,3.543982e+05,2.661810e+07
life_expectancy,210.0,7.284412e+01,7.465994e+00,5.280500e+01,6.783450e+01,7.413100e+01,7.815427e+01,8.541707e+01
smoking_prevalence,210.0,2.168381e+01,8.100477e+00,2.000000e+00,1.682500e+01,2.180000e+01,2.495000e+01,4.700000e+01
diabetes_prevalence,210.0,8.353333e+00,4.723211e+00,1.000000e+00,5.400000e+00,6.900000e+00,1.062500e+01,3.050000e+01
infant_mortality_rate,210.0,2.078714e+01,1.873542e+01,1.400000e+00,6.250000e+00,1.400000e+01,3.030000e+01,8.450000e+01
adult_male_mortality_rate,210.0,1.844716e+02,8.765893e+01,4.149800e+01,1.179672e+02,1.775390e+02,2.349907e+02,5.456750e+02
adult_female_mortality_rate,210.0,1.197452e+02,7.795545e+01,2.448700e+01,6.337825e+01,9.557900e+01,1.522713e+02,4.193630e+02
pollution_mortality_rate,210.0,8.917667e+01,6.759329e+01,7.000000e+00,3.837500e+01,6.860000e+01,1.366500e+02,3.241000e+02
comorbidity_mortality_rate,210.0,1.886810e+01,5.229076e+00,7.800000e+00,1.587500e+01,1.880000e+01,2.227500e+01,3.060000e+01
hospital_beds_per_1000,210.0,2.386667e+00,9.010963e-01,3.000000e-01,2.300000e+00,2.300000e+00,2.300000e+00,1.150000e+01
nurses_per_1000,210.0,4.203901e+00,3.848589e+00,7.370000e-02,1.468075e+00,3.067050e+00,5.732350e+00,1.946140e+01
physicians_per_1000,210.0,1.843686e+00,1.466303e+00,1.400000e-02,7.245000e-01,1.576550e+00,2.611925e+00,8.421800e+00
health_expenditure_usd,210.0,9.959128e+02,1.692947e+03,1.943165e+01,1.048312e+02,3.359494e+02,9.686554e+02,1.024614e+04
out_of_pocket_health_expenditure_usd,210.0,2.132552e+02,3.245071e+02,1.923640e-01,3.375467e+01,9.275792e+01,2.364889e+02,2.882037e+03

--- בדיקת ערכים חסרים (Missing Values) בקובץ הבריאות המעובד ---

                                      כמות ערכי NULL  אחוז ערכי NULL
location_key                                       1         0.47619
country_code                                       1         0.47619
country_name                                       0         0.00000
aggregation_level                                  0         0.00000
population                                         0         0.00000
population_male                                    0         0.00000
population_female                                  0         0.00000
population_rural                                   0         0.00000
population_urban                                   0         0.00000
population_largest_city                            0         0.00000
population_clustered                               0         0.00000
population_density                                 0         0.00000
human_development_index                            0         0.00000
population_age_00_09                               0         0.00000
population_age_10_19                               0         0.00000
population_age_20_29                               0         0.00000
population_age_30_39                               0         0.00000
population_age_40_49                               0         0.00000
population_age_50_59                               0         0.00000
population_age_60_69                               0         0.00000
population_age_70_79                               0         0.00000
population_age_80_and_older                        0         0.00000
life_expectancy                                    0         0.00000
smoking_prevalence                                 0         0.00000
diabetes_prevalence                                0         0.00000
infant_mortality_rate                              0         0.00000
adult_male_mortality_rate                          0         0.00000
adult_female_mortality_rate                        0         0.00000
pollution_mortality_rate                           0         0.00000
comorbidity_mortality_rate                         0         0.00000
hospital_beds_per_1000                             0         0.00000
nurses_per_1000                                    0         0.00000
physicians_per_1000                                0         0.00000
health_expenditure_usd                             0         0.00000
out_of_pocket_health_expenditure_usd               0         0.00000

--- מדדי התפלגות מורחבים של עמודות הבריאות ---

                                      Skewness (צידוד)  Kurtosis (גבנוניות)
aggregation_level                             0.000000             0.000000
population                                    8.758225            82.371035
population_male                               8.837073            83.461790
population_female                             8.672384            81.194140
population_rural                              9.927455           107.656077
population_urban                              8.709356            89.363822
population_largest_city                       3.348164            13.344587
population_clustered                          8.833982            90.576830
population_density                            9.005497            85.636883
human_development_index                      -0.477150            -0.516441
population_age_00_09                          8.242295            77.975518
population_age_10_19                          8.957616            90.911761
population_age_20_29                          8.913342            87.072393
population_age_30_39                          8.971946            85.529646
population_age_40_49                          9.214126            91.185104
population_age_50_59                         10.073039           111.705021
population_age_60_69                          9.778184           106.488737
population_age_70_79                          9.081210            94.980704
population_age_80_and_older                   7.394924            65.687461
life_expectancy                              -0.599701            -0.293148
smoking_prevalence                            0.325928             0.766694
diabetes_prevalence                           1.392492             2.621186
infant_mortality_rate                         1.271807             0.963575
adult_male_mortality_rate                     0.921819             1.383253
adult_female_mortality_rate                   1.367069             1.510506
pollution_mortality_rate                      1.026387             0.498807
comorbidity_mortality_rate                    0.026320            -0.345611
hospital_beds_per_1000                        6.035522            53.841470
nurses_per_1000                               1.620157             2.597731
physicians_per_1000                           1.167809             1.974032
health_expenditure_usd                        2.890991             9.443216
out_of_pocket_health_expenditure_usd          3.858999            23.387257

## Re-arrainging the data in file "ICT_GHS_Ind_md.csv":
Re-arrainging the data in file "ICT_GHS_Ind_md":
1. Eliminating "Subregion" fields
2. Print file EDA
##

In [ ]:
import os
import pandas as pd

# =====================================================================
# 1. הגדרת נתיב הספרייה ושם הקובץ הטכנולוגי (ICT ו-GHS)
# =====================================================================
FOLDER_PATH = '/content/drive/MyDrive/DS_IsTheWorldReadyForTheNextPandemic/DATASET TO USE/'
FILE_NAME = 'ICT_GHS_Ind_md.csv'  # שם הקובץ המדויק שציינתן

FULL_PATH = os.path.join(FOLDER_PATH, FILE_NAME)
print(f"טוען את הקובץ מתוך: {FULL_PATH}")

# טעינת הקובץ וניקוי רווחים מיותרים משמות העמודות ליתר ביטחון
df_ict_ghs = pd.read_csv(FULL_PATH)
df_ict_ghs.columns = df_ict_ghs.columns.str.strip()

# =====================================================================
# 2. הסרת עמודות K, L, M, N (עמודות באינדקסים 10, 11, 12, 13)
# =====================================================================
# משיכת שמות עמודות ה-subregion לפי מיקומן המדויק (K=10, L=11, M=12, N=13)
columns_to_drop = [
    df_ict_ghs.columns[10],
    df_ict_ghs.columns[11],
    df_ict_ghs.columns[12],
    df_ict_ghs.columns[13]
]
df_ict_ghs_cleaned = df_ict_ghs.drop(columns=columns_to_drop)

# =====================================================================
# 3. מילוי כל השדות הריקים (Null / NaN) במספר 0
# =====================================================================
df_ict_ghs_cleaned = df_ict_ghs_cleaned.fillna(0)

# =====================================================================
# 4. שמירת הקובץ הנקי החדש באותה ספרייה
# =====================================================================
OUTPUT_NAME = 'cleaned_ICT_GHS_final.csv'
OUTPUT_PATH = os.path.join(FOLDER_PATH, OUTPUT_NAME)
df_ict_ghs_cleaned.to_csv(OUTPUT_PATH, index=False)

print("\n--- הקובץ עובד ונוקה בהצלחה! ---")
print(f"1. עמודות K, L, M, N (עמודות המחוזות) הוסרו מהטבלה.")
print(f"2. כל השדות הריקים מולאו ב-0.")
print(f"3. הקובץ הנקי נשמר בשם: {OUTPUT_NAME}")
print(f"מימדי הטבלה החדשה (שורות, עמודות): {df_ict_ghs_cleaned.shape}")

# =====================================================================
# 5. הדפסת 10 השורות הראשונות לבדיקה ויזואלית סופית
# =====================================================================
print("\n--- 10 השורות הראשונות בטבלת הטכנולוגיה והמדדים הנקייה ---")
display(df_ict_ghs_cleaned.head(10))

טוען את הקובץ מתוך: /content/drive/MyDrive/DS_IsTheWorldReadyForTheNextPandemic/DATASET TO USE/ICT_GHS_Ind_md.csv

--- הקובץ עובד ונוקה בהצלחה! ---
1. עמודות K, L, M, N (עמודות המחוזות) הוסרו מהטבלה.
2. כל השדות הריקים מולאו ב-0.
3. הקובץ הנקי נשמר בשם: cleaned_ICT_GHS_final.csv
מימדי הטבלה החדשה (שורות, עמודות): (352, 323)

--- 10 השורות הראשונות בטבלת הטכנולוגיה והמדדים הנקייה ---

,Entity,Code,Year,Landline phone subscriptions,Landline Internet subscriptions,Mobile phone subscriptions,Internet users,location_key,country_code,country_name,...,6.5.1d) Tobacco use (% of adults),6.5.1e) Level of adult obesity (%),6.5.2) Access to potable water and sanitation,6.5.2a) Access to potable water,6.5.2b) Access to at least basic sanitation facilities,6.5.3) Public healthcare spending levels per capita,6.5.3a) Domestic general government health expenditure per capita (PPP),6.5.4) Trust in medical and health advice,6.5.4a) Trust medical and health advice from the government,6.5.4b) Trust medical and health advice from medical workers
0,Afghanistan,AFG,2019,0.356,0.051994,59.6471,17.6000,AF,AF,Afghanistan,...,48.6,94.2,37.1,37.5,36.7,0.1,0.1,75,100,50
1,Afghanistan,AFG,2021,0.364,0.066424,56.6945,16.5143,AF,AF,Afghanistan,...,49.4,94.2,43.2,47.1,39.4,0.1,0.1,75,100,50
2,Albania,ALB,2019,8.420,15.119300,91.1635,68.5504,AL,AL,Albania,...,48.4,66.7,92.6,86.7,98.6,6.1,6.1,25,0,50
3,Albania,ALB,2021,6.940,19.630400,92.4843,79.3237,AL,AL,Albania,...,47.3,66.7,92.7,86.7,98.6,6.4,6.4,25,0,50
4,Algeria,DZA,2019,10.700,8.275270,104.9220,55.7907,DZ,DZ,Algeria,...,69.6,57.0,89.2,90.8,87.5,12.5,12.5,25,0,50
5,Algeria,DZA,2021,11.400,9.331840,105.0370,72.2124,DZ,DZ,Algeria,...,68.8,57.0,89.3,91.0,87.6,10.8,10.8,25,0,50
6,Andorra,AND,2019,51.900,47.543000,114.9530,90.7187,AD,AD,Andorra,...,40.0,60.1,100.0,100.0,100.0,39.5,39.5,50,50,50
7,Andorra,AND,2021,63.500,50.276900,119.6880,93.8975,AD,AD,Andorra,...,37.8,60.1,100.0,100.0,100.0,42.1,42.1,50,50,50
8,Angola,AGO,2019,0.385,0.367770,45.8065,32.1294,AO,AO,Angola,...,78.8,89.6,34.7,25.5,44.0,1.4,1.4,50,50,50
9,Angola,AGO,2021,0.348,0.390925,44.3869,39.3876,AO,AO,Angola,...,78.6,89.6,37.4,28.4,46.5,1.1,1.1,50,50,50

In [ ]:
# 1. מדדי מרכז ופיזור (ממוצע, חציון, סטיית תקן, מינימום, מקסימום ואחוזונים)
print("--- מדדי מרכז ופיזור עבור מדדי הטכנולוגיה וביטחון הבריאות (GHSI) ---")
# שימוש ב-.T הופך את הטבלה ומקל מאוד על קריאת המדדים של תתי-הקטגוריות הרבות במדד ה-GHS
display(df_ict_ghs_cleaned.describe().T)

# 2. וידאו סופי שאין ערכים חסרים (התוצאה בכל העמודות צריכה להיות 0)
print("\n--- בדיקת ערכים חסרים (Missing Values) בקובץ ה-ICT וה-GHS המעובד ---")
missing_summary = pd.DataFrame({
    'כמות ערכי NULL': df_ict_ghs_cleaned.isnull().sum(),
    'אחוז ערכי NULL': (df_ict_ghs_cleaned.isnull().sum() / len(df_ict_ghs_cleaned)) * 100
})
display(missing_summary)

# 3. מדדי התפלגות (צידוד וגבנוניות - Skewness & Kurtosis)
print("\n--- מדדי התפלגות מורחבים של עמודות הטכנולוגיה והמדדים ---")
distribution_stats = pd.DataFrame({
    'Skewness (צידוד)': df_ict_ghs_cleaned.select_dtypes(include=['number']).skew(),
    'Kurtosis (גבנוניות)': df_ict_ghs_cleaned.select_dtypes(include=['number']).kurt()
})
display(distribution_stats)

--- מדדי מרכז ופיזור עבור מדדי הטכנולוגיה וביטחון הבריאות (GHSI) ---

,count,mean,std,min,25%,50%,75%,max
Year,352.0,2020.000000,1.001423,2019.0000,2019.000000,2020.000000,2021.000000,2021.0000
Landline phone subscriptions,352.0,14.966468,16.756547,0.0000,1.477500,11.150000,22.100000,118.0000
Landline Internet subscriptions,352.0,14.951916,15.094109,0.0000,1.013927,9.872825,27.710625,54.9173
Mobile phone subscriptions,352.0,106.705579,35.518960,16.3341,84.815225,110.674500,131.053250,209.0330
Internet users,352.0,60.007142,30.796983,0.0000,34.476625,69.664500,85.440400,100.0000
...,...,...,...,...,...,...,...,...
6.5.3) Public healthcare spending levels per capita,352.0,17.404830,22.563056,0.0000,1.100000,6.950000,24.600000,100.0000
6.5.3a) Domestic general government health expenditure per capita (PPP),352.0,17.404830,22.563056,0.0000,1.100000,6.950000,24.600000,100.0000
6.5.4) Trust in medical and health advice,352.0,61.647727,24.590337,0.0000,50.000000,50.000000,75.000000,100.0000
6.5.4a) Trust medical and health advice from the government,352.0,53.409091,29.035252,0.0000,50.000000,50.000000,50.000000,100.0000
6.5.4b) Trust medical and health advice from medical workers,352.0,69.886364,27.258155,0.0000,50.000000,50.000000,100.000000,100.0000

--- בדיקת ערכים חסרים (Missing Values) בקובץ ה-ICT וה-GHS המעובד ---

,כמות ערכי NULL,אחוז ערכי NULL
Entity,0,0.0
Code,0,0.0
Year,0,0.0
Landline phone subscriptions,0,0.0
Landline Internet subscriptions,0,0.0
...,...,...
6.5.3) Public healthcare spending levels per capita,0,0.0
6.5.3a) Domestic general government health expenditure per capita (PPP),0,0.0
6.5.4) Trust in medical and health advice,0,0.0
6.5.4a) Trust medical and health advice from the government,0,0.0
6.5.4b) Trust medical and health advice from medical workers,0,0.0

--- מדדי התפלגות מורחבים של עמודות הטכנולוגיה והמדדים ---

,Skewness (צידוד),Kurtosis (גבנוניות)
Year,0.000000,-2.011461
Landline phone subscriptions,1.949936,6.839351
Landline Internet subscriptions,0.695342,-0.837335
Mobile phone subscriptions,-0.252819,-0.247877
Internet users,-0.596725,-0.942628
...,...,...
6.5.3) Public healthcare spending levels per capita,1.614774,1.828294
6.5.3a) Domestic general government health expenditure per capita (PPP),1.614774,1.828294
6.5.4) Trust in medical and health advice,0.041384,-0.265596
6.5.4a) Trust medical and health advice from the government,-0.004716,-0.049637
6.5.4b) Trust medical and health advice from medical workers,-0.117012,-0.968347

## Merging File "vaccinations_Ind_md.csv" with file "epidemiology_Ind_md.csv":
1. Merging the two files into one file with fully outer join:
2. Print first 10 lines and statistices
##

In [ ]:
import os
import pandas as pd

# יצירת כינוי תואם לקובץ האפידמיולוגיה השנתי בזיכרון
df_epi_yearly = df_yearly.copy()

# (בהנחה ששני המשתנים df_epi_yearly ו-df_vac_yearly קיימים כרגע בזיכרון שלכן)

# =====================================================================
# 1. הגדרת העמודות המשותפות שאין צורך לשכפל (עמודות מזהות)
# =====================================================================
# לפני המיזוג, נוריד את country_code ו-country_name מטבלת החיסונים
# כדי שלא נקבל עמודות כפולות כמו country_name_x ו-country_name_y
cols_to_drop_from_vac = ['country_code', 'country_name', 'aggregation_level']
df_vac_filtered = df_vac_yearly.drop(columns=[col for col in cols_to_drop_from_vac if col in df_vac_yearly.columns])

# =====================================================================
# 2. ביצוע ה-Full Outer Join לפי מדינה (location_key) ושנה (YEAR)
# =====================================================================
print("מבצע מיזוג חיצוני מלא (Full Outer Join)...")
df_merged_2 = pd.merge(
    df_epi_yearly,
    df_vac_filtered,
    on=['location_key', 'YEAR'],
    how='outer'
)

# =====================================================================
# 3. ניקוי שלאחר המיזוג: מילוי ערכי NaN שנוצרו מה-Outer Join
# =====================================================================
# בעקבות החיבור החיצוני, שורות שלא התאימו בשתי הטבלאות יקבלו NaN. נשלים אותן ל-0.
df_merged_2 = df_merged_2.fillna(0)

# =====================================================================
# 4. שמירת הקובץ המאוחד החדש
# =====================================================================
# הגדירו את ה-PATH שלכן לשמירה
FOLDER_PATH = '/content/drive/MyDrive/DS_IsTheWorldReadyForTheNextPandemic/DATASET TO USE/'
OUTPUT_NAME = 'merged_epidemiology_vaccinations_yearly_md.csv'
OUTPUT_PATH = os.path.join(FOLDER_PATH, OUTPUT_NAME)

df_merged_2.to_csv(OUTPUT_PATH, index=False)

print(f"\n--- המיזוג (מיזוג 2) הסתיים בהצלחה! ---")
print(f"הקובץ המאוחד נשמר בשם: {OUTPUT_NAME}")
print(f"מימדי הטבלה המאוחדת (שורות, עמודות): {df_merged_2.shape}")

מבצע מיזוג חיצוני מלא (Full Outer Join)...

--- המיזוג (מיזוג 2) הסתיים בהצלחה! ---
הקובץ המאוחד נשמר בשם: merged_epidemiology_vaccinations_yearly_md.csv
מימדי הטבלה המאוחדת (שורות, עמודות): (700, 43)

In [ ]:
# =====================================================================
# 1. הדפסת 10 השורות הראשונות של הטבלה המאוחדת החדשה
# =====================================================================
print("--- 10 השורות הראשונות בטבלה המאוחדת (אפידמיולוגיה + חיסונים) ---")
display(df_merged_2.head(10))

# =====================================================================
# 2. הפקת מדדים סטטיסטיים מקיפים (מרכז ופיזור)
# =====================================================================
print("\n--- מדדי מרכז ופיזור עבור כל העמודות המספריות בטבלה המאוחדת ---")
# שימוש ב-.T (טרנספוזיציה) הופך את הטבלה ומקל על קריאת עמודות התחלואה והחיסונים יחד
display(df_merged_2.describe().T)

# =====================================================================
# 3. וידאו סופי שאין ערכים חסרים (NaN) לאחר פעולת ה-fillna
# =====================================================================
print("\n--- בדיקת ערכים חסרים (Missing Values) בקובץ המאוחד ---")
missing_summary = pd.DataFrame({
    'כמות ערכי NULL': df_merged_2.isnull().sum(),
    'אחוז ערכי NULL': (df_merged_2.isnull().sum() / len(df_merged_2)) * 100
})
display(missing_summary)

--- 10 השורות הראשונות בטבלה המאוחדת (אפידמיולוגיה + חיסונים) ---

,location_key,YEAR,country_code,country_name,aggregation_level,new_confirmed,new_deceased,new_recovered,new_tested,cumulative_confirmed,...,new_persons_fully_vaccinated_janssen,cumulative_persons_fully_vaccinated_janssen,new_vaccine_doses_administered_janssen,cumulative_vaccine_doses_administered_janssen,new_persons_vaccinated_sinovac,total_persons_vaccinated_sinovac,new_persons_fully_vaccinated_sinovac,total_persons_fully_vaccinated_sinovac,new_vaccine_doses_administered_sinovac,total_vaccine_doses_administered_sinovac
0,0,2020,0,Namibia,0.0,24536.0,208.0,0.0,199795.0,24536.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,0,2021,0,Namibia,0.0,124942.0,3447.0,0.0,599977.0,149478.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,0,2022,0,Namibia,0.0,17167.0,422.0,0.0,47299.0,166645.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,AD,2020,AD,Andorra,0.0,8117.0,84.0,0.0,0.0,8117.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,AD,2021,AD,Andorra,0.0,15623.0,56.0,0.0,0.0,23740.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
5,AD,2022,AD,Andorra,0.0,22407.0,15.0,0.0,0.0,46147.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
6,AE,2020,AE,United Arab Emirates,0.0,209678.0,671.0,0.0,21035504.0,209678.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
7,AE,2021,AE,United Arab Emirates,0.0,554815.0,1494.0,0.0,91095231.0,764493.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
8,AE,2022,AE,United Arab Emirates,0.0,256698.0,177.0,0.0,56391937.0,1021191.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
9,AF,2020,AF,Afghanistan,0.0,52586.0,2211.0,0.0,0.0,52586.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

--- מדדי מרכז ופיזור עבור כל העמודות המספריות בטבלה המאוחדת ---

,count,mean,std,min,25%,50%,75%,max
YEAR,700.0,2.020996e+03,8.225950e-01,2019.0,2020.00,2021.0,2022.00,2.022000e+03
aggregation_level,700.0,0.000000e+00,0.000000e+00,0.0,0.00,0.0,0.00,0.000000e+00
new_confirmed,700.0,8.692035e+05,3.259371e+06,0.0,5466.50,39149.5,343313.50,3.878153e+07
new_deceased,700.0,9.230770e+03,3.625106e+04,0.0,35.75,353.0,3416.25,4.379340e+05
new_recovered,700.0,4.672222e+05,5.915128e+06,-252396.0,0.00,0.0,0.00,1.306439e+08
new_tested,700.0,7.231386e+06,3.501383e+07,0.0,0.00,15618.5,1770932.50,4.958196e+08
cumulative_confirmed,700.0,1.386583e+06,5.680185e+06,0.0,8192.00,71512.0,551334.00,9.244050e+07
cumulative_deceased,700.0,1.936206e+04,7.488487e+04,0.0,86.00,881.0,7645.00,1.005195e+06
cumulative_recovered,700.0,8.320684e+05,1.084563e+07,0.0,0.00,0.0,0.00,2.345841e+08
cumulative_tested,700.0,2.902517e+07,3.549852e+08,0.0,0.00,316641.0,4746493.75,9.214000e+09
new_persons_vaccinated,700.0,6.762888e+06,4.363973e+07,0.0,0.00,40759.0,1554941.25,8.456406e+08
cumulative_persons_vaccinated,700.0,1.417082e+07,8.773179e+07,0.0,0.00,156496.5,4279454.50,1.302773e+09
new_persons_fully_vaccinated,700.0,5.904573e+06,3.396435e+07,0.0,0.00,36152.0,1305122.50,6.032172e+08
cumulative_persons_fully_vaccinated,700.0,1.255392e+07,8.090191e+07,0.0,0.00,81262.0,3292537.00,1.270656e+09
new_vaccine_doses_administered,700.0,1.774173e+07,1.293090e+08,0.0,0.00,133465.5,3617267.50,2.836769e+09
cumulative_vaccine_doses_administered,700.0,3.072055e+07,2.006368e+08,0.0,0.00,265914.5,8215044.50,3.434774e+09
new_persons_vaccinated_pfizer,700.0,2.229943e+04,5.206441e+05,0.0,0.00,0.0,0.00,1.363560e+07
cumulative_persons_vaccinated_pfizer,700.0,4.177885e+04,7.828338e+05,0.0,0.00,0.0,0.00,1.560960e+07
new_persons_fully_vaccinated_pfizer,700.0,1.823451e+05,3.816130e+06,0.0,0.00,0.0,0.00,9.921628e+07
cumulative_persons_fully_vaccinated_pfizer,700.0,3.911704e+05,6.602016e+06,0.0,0.00,0.0,0.00,1.292668e+08
new_vaccine_doses_administered_pfizer,700.0,4.509954e+05,9.740515e+06,0.0,0.00,0.0,0.00,2.490339e+08
cumulative_vaccine_doses_administered_pfizer,700.0,9.405419e+05,1.767350e+07,0.0,0.00,0.0,0.00,3.625211e+08
new_persons_vaccinated_moderna,700.0,0.000000e+00,0.000000e+00,0.0,0.00,0.0,0.00,0.000000e+00
cumulative_persons_vaccinated_moderna,700.0,0.000000e+00,0.000000e+00,0.0,0.00,0.0,0.00,0.000000e+00
new_persons_fully_vaccinated_moderna,700.0,9.081457e+04,2.231704e+06,0.0,0.00,0.0,0.00,5.886424e+07
cumulative_persons_fully_vaccinated_moderna,700.0,2.162791e+05,4.045274e+06,0.0,0.00,0.0,0.00,7.805066e+07
new_vaccine_doses_administered_moderna,700.0,2.653610e+05,5.790636e+06,0.0,0.00,0.0,0.00,1.487143e+08
cumulative_vaccine_doses_administered_moderna,700.0,6.062005e+05,1.137607e+07,0.0,0.00,0.0,0.00,2.306894e+08
new_persons_vaccinated_janssen,700.0,0.000000e+00,0.000000e+00,0.0,0.00,0.0,0.00,0.000000e+00
cumulative_persons_vaccinated_janssen,700.0,0.000000e+00,0.000000e+00,0.0,0.00,0.0,0.00,0.000000e+00
new_persons_fully_vaccinated_janssen,700.0,2.413162e+04,6.098945e+05,0.0,0.00,0.0,0.00,1.611886e+07
cumulative_persons_fully_vaccinated_janssen,700.0,4.775228e+04,8.929637e+05,0.0,0.00,0.0,0.00,1.709994e+07
new_vaccine_doses_administered_janssen,700.0,2.668528e+04,6.595493e+05,0.0,0.00,0.0,0.00,1.740526e+07
cumulative_vaccine_doses_administered_janssen,700.0,5.214590e+04,9.754582e+05,0.0,0.00,0.0,0.00,1.888829e+07
new_persons_vaccinated_sinovac,700.0,1.456327e+04,3.825708e+05,0.0,0.00,0.0,0.00,1.012172e+07
total_persons_vaccinated_sinovac,700.0,2.756471e+02,7.186244e+03,0.0,0.00,0.0,0.00,1.901130e+05
new_persons_fully_vaccinated_sinovac,700.0,0.000000e+00,0.000000e+00,0.0,0.00,0.0,0.00,0.000000e+00
total_persons_fully_vaccinated_sinovac,700.0,0.000000e+00,0.000000e+00,0.0,0.00,0.0,0.00,0.000000e+00
new_vaccine_doses_administered_sinovac,700.0,0.000000e+00,0.000000e+00,0.0,0.00,0.0,0.00,0.000000e+00
total_vaccine_doses_administered_sinovac,700.0,0.000000e+00,0.000000e+00,0.0,0.00,0.0,0.00,0.000000e+00

--- בדיקת ערכים חסרים (Missing Values) בקובץ המאוחד ---

                                               כמות ערכי NULL  אחוז ערכי NULL
location_key                                                0             0.0
YEAR                                                        0             0.0
country_code                                                0             0.0
country_name                                                0             0.0
aggregation_level                                           0             0.0
new_confirmed                                               0             0.0
new_deceased                                                0             0.0
new_recovered                                               0             0.0
new_tested                                                  0             0.0
cumulative_confirmed                                        0             0.0
cumulative_deceased                                         0             0.0
cumulative_recovered                                        0             0.0
cumulative_tested                                           0             0.0
new_persons_vaccinated                                      0             0.0
cumulative_persons_vaccinated                               0             0.0
new_persons_fully_vaccinated                                0             0.0
cumulative_persons_fully_vaccinated                         0             0.0
new_vaccine_doses_administered                              0             0.0
cumulative_vaccine_doses_administered                       0             0.0
new_persons_vaccinated_pfizer                               0             0.0
cumulative_persons_vaccinated_pfizer                        0             0.0
new_persons_fully_vaccinated_pfizer                         0             0.0
cumulative_persons_fully_vaccinated_pfizer                  0             0.0
new_vaccine_doses_administered_pfizer                       0             0.0
cumulative_vaccine_doses_administered_pfizer                0             0.0
new_persons_vaccinated_moderna                              0             0.0
cumulative_persons_vaccinated_moderna                       0             0.0
new_persons_fully_vaccinated_moderna                        0             0.0
cumulative_persons_fully_vaccinated_moderna                 0             0.0
new_vaccine_doses_administered_moderna                      0             0.0
cumulative_vaccine_doses_administered_moderna               0             0.0
new_persons_vaccinated_janssen                              0             0.0
cumulative_persons_vaccinated_janssen                       0             0.0
new_persons_fully_vaccinated_janssen                        0             0.0
cumulative_persons_fully_vaccinated_janssen                 0             0.0
new_vaccine_doses_administered_janssen                      0             0.0
cumulative_vaccine_doses_administered_janssen               0             0.0
new_persons_vaccinated_sinovac                              0             0.0
total_persons_vaccinated_sinovac                            0             0.0
new_persons_fully_vaccinated_sinovac                        0             0.0
total_persons_fully_vaccinated_sinovac                      0             0.0
new_vaccine_doses_administered_sinovac                      0             0.0
total_vaccine_doses_administered_sinovac                    0             0.0

## Merging File "epidemiology_Ind_md.csv" with file "demographic_Ind_md.csv" with file:
1. Merging the two files into one file with Left join in order to maintain all
data.
2. Print first 10 lines and statistices
3. Calculating X4 = New Tested / Population * 1000 (Normalized)
##

In [ ]:
import os
import pandas as pd

# (בהנחה ששני המשתנים df_yearly ו-df_demo_cleaned קיימים כרגע בזיכרון שלכן)

# =====================================================================
# 1. ניקוי עמודות כפולות מטבלת הדמוגרפיה לפני החיבור
# =====================================================================
cols_to_drop_from_demo = ['country_code', 'country_name', 'aggregation_level']
df_demo_filtered = df_demo_cleaned.drop(columns=[col for col in cols_to_drop_from_demo if col in df_demo_cleaned.columns])

# =====================================================================
# 2. ביצוע ה-Left Join לפי מפתח המדינה (location_key)
# =====================================================================
print("מבצע מיזוג שמאלי (Left Join) של נתוני אפידמיולוגיה ודמוגרפיה...")
df_epidemiology_demographics = pd.merge(
    df_yearly,          # טבלת הבסיס השנתית (האפידמיולוגית)
    df_demo_filtered,   # טבלת הדמוגרפיה המסוננת
    on='location_key',  # החיבור מתבצע לפי מפתח המדינה
    how='left'          # שמירה על כל שורות התחלואה והתאמת הדמוגרפיה אליהן
)

# =====================================================================
# 3. ניקוי שלאחר המיזוג: מילוי ערכים חסרים (NaN) מבוקר ולא גורף
# =====================================================================
# נמלא ב-0 רק עמודות של מונים אפידמיולוגיים יומיים/שנתיים שבהם NaN מייצג אפס מקרים
cols_to_fill_zero = ['new_confirmed', 'new_deceased', 'total_confirmed', 'total_deceased']
for col in cols_to_fill_zero:
    if col in df_epidemiology_demographics.columns:
        df_epidemiology_demographics[col] = df_epidemiology_demographics[col].fillna(0)

# שאר עמודות השיעורים, המדדים והתמותה העודפת נשארות כ-NaN כדי לא לעוות את הנתונים

# =====================================================================
# 4. שמירת הקובץ המאוחד החדש
# =====================================================================
FOLDER_PATH = '/content/drive/MyDrive/DS_IsTheWorldReadyForTheNextPandemic/DATASET TO USE/'
OUTPUT_NAME = 'merged_epidemiology_demographics_yearly.csv'
OUTPUT_PATH = os.path.join(FOLDER_PATH, OUTPUT_NAME)

df_epidemiology_demographics.to_csv(OUTPUT_PATH, index=False)

print(f"\n--- המיזוג (מיזוג 4 בתוכנית) הסתיים בהצלחה! ---")
print(f"הקובץ המאוחד נשמר בשם: {OUTPUT_NAME}")
print(f"מימדי הטבלה המאוחדת החדשה (שורות, עמודות): {df_epidemiology_demographics.shape}")

מבצע מיזוג שמאלי (Left Join) של נתוני אפידמיולוגיה ודמוגרפיה...

--- המיזוג (מיזוג 4 בתוכנית) הסתיים בהצלחה! ---
הקובץ המאוחד נשמר בשם: merged_epidemiology_demographics_yearly.csv
מימדי הטבלה המאוחדת החדשה (שורות, עמודות): (699, 31)

In [ ]:
# =====================================================================
# 1. הדפסת 10 השורות הראשונות של הטבלה המאוחדת החדשה
# =====================================================================
print("--- 10 השורות הראשונות בטבלה המאוחדת (אפידמיולוגיה + דמוגרפיה) ---")
display(df_epidemiology_demographics.head(10))

# =====================================================================
# 2. הפקת מדדים סטטיסטיים מקיפים (מרכז ופיזור)
# =====================================================================
print("\n--- מדדי מרכז ופיזור עבור כל העמודות המספריות בטבלה המאוחדת ---")
# שימוש ב-.T (טרנספוזיציה) הופך את הטבלה ומקל על קריאת עמודות התחלואה והדמוגרפיה יחד
display(df_epidemiology_demographics.describe().T)

# =====================================================================
# 3. וידאו סופי שאין ערכים חסרים (NaN) לאחר פעולת ה-Left Join
# =====================================================================
print("\n--- בדיקת ערכים חסרים (Missing Values) בקובץ המאוחד ---")
missing_summary = pd.DataFrame({
    'כמות ערכי NULL': df_epidemiology_demographics.isnull().sum(),
    'אחוז ערכי NULL': (df_epidemiology_demographics.isnull().sum() / len(df_epidemiology_demographics)) * 100
})
display(missing_summary)

--- 10 השורות הראשונות בטבלה המאוחדת (אפידמיולוגיה + דמוגרפיה) ---

,location_key,YEAR,country_code,country_name,aggregation_level,new_confirmed,new_deceased,new_recovered,new_tested,cumulative_confirmed,...,human_development_index,population_age_00_09,population_age_10_19,population_age_20_29,population_age_30_39,population_age_40_49,population_age_50_59,population_age_60_69,population_age_70_79,population_age_80_and_older
0,0,2020,0,Namibia,0,24536.0,208.0,0.0,199795.0,24536.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,0,2021,0,Namibia,0,124942.0,3447.0,0.0,599977.0,149478.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,0,2022,0,Namibia,0,17167.0,422.0,0.0,47299.0,166645.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,AD,2020,AD,Andorra,0,8117.0,84.0,0.0,0.0,8117.0,...,0.858,9370.0,12022.0,10727.0,12394.0,21001.0,20720.0,14433.0,8657.0,4881.0
4,AD,2021,AD,Andorra,0,15623.0,56.0,0.0,0.0,23740.0,...,0.858,9370.0,12022.0,10727.0,12394.0,21001.0,20720.0,14433.0,8657.0,4881.0
5,AD,2022,AD,Andorra,0,22407.0,15.0,0.0,0.0,46147.0,...,0.858,9370.0,12022.0,10727.0,12394.0,21001.0,20720.0,14433.0,8657.0,4881.0
6,AE,2020,AE,United Arab Emirates,0,209678.0,671.0,0.0,21035504.0,209678.0,...,0.863,1011713.0,842991.0,2149343.0,3169314.0,1608109.0,797913.0,242707.0,55884.0,12426.0
7,AE,2021,AE,United Arab Emirates,0,554815.0,1494.0,0.0,91095231.0,764493.0,...,0.863,1011713.0,842991.0,2149343.0,3169314.0,1608109.0,797913.0,242707.0,55884.0,12426.0
8,AE,2022,AE,United Arab Emirates,0,256698.0,177.0,0.0,56391937.0,1021191.0,...,0.863,1011713.0,842991.0,2149343.0,3169314.0,1608109.0,797913.0,242707.0,55884.0,12426.0
9,AF,2020,AF,Afghanistan,0,52586.0,2211.0,0.0,0.0,52586.0,...,0.498,11088732.0,9821559.0,7035871.0,4534646.0,2963459.0,1840198.0,1057496.0,480455.0,105925.0

--- מדדי מרכז ופיזור עבור כל העמודות המספריות בטבלה המאוחדת ---

,count,mean,std,min,25%,50%,75%,max
YEAR,699.0,2.020996e+03,8.231841e-01,2019.000,2020.000,2021.000,2.022000e+03,2.022000e+03
aggregation_level,699.0,0.000000e+00,0.000000e+00,0.000,0.000,0.000,0.000000e+00,0.000000e+00
new_confirmed,699.0,8.704470e+05,3.261539e+06,0.000,5565.500,39515.000,3.447160e+05,3.878153e+07
new_deceased,699.0,9.243976e+03,3.627533e+04,0.000,36.000,354.000,3.426500e+03,4.379340e+05
new_recovered,699.0,4.678906e+05,5.919337e+06,-252396.000,0.000,0.000,0.000000e+00,1.306439e+08
new_tested,699.0,7.241731e+06,3.503783e+07,0.000,0.000,15769.000,1.782367e+06,4.958196e+08
cumulative_confirmed,699.0,1.388567e+06,5.684010e+06,0.000,8273.000,71815.000,5.532500e+05,9.244050e+07
cumulative_deceased,699.0,1.938976e+04,7.493490e+04,0.000,86.500,884.000,7.659000e+03,1.005195e+06
cumulative_recovered,699.0,8.332587e+05,1.085335e+07,0.000,0.000,0.000,0.000000e+00,2.345841e+08
cumulative_tested,699.0,2.906669e+07,3.552377e+08,0.000,0.000,323516.000,4.761612e+06,9.214000e+09
population,696.0,3.366208e+07,1.357143e+08,50.000,479540.000,5518092.000,2.141325e+07,1.439324e+09
population_male,696.0,1.699886e+07,6.982988e+07,634.000,304489.500,2889073.000,1.044471e+07,7.382473e+08
population_female,696.0,1.671504e+07,6.588677e+07,683.000,283020.250,2789344.000,1.114590e+07,7.010764e+08
population_rural,696.0,1.479532e+07,7.062783e+07,0.000,224662.250,1758851.000,9.512141e+06,8.953862e+08
population_urban,696.0,1.885939e+07,6.865037e+07,5464.000,632210.750,3850231.000,1.046879e+07,8.429340e+08
population_largest_city,696.0,3.736764e+06,5.041536e+06,342743.000,1601534.750,2159137.000,2.946158e+06,3.743519e+07
population_clustered,696.0,9.363793e+06,3.231089e+07,1026758.000,3059914.250,3137690.000,3.245021e+06,3.989761e+08
population_density,696.0,4.729012e+02,2.345486e+03,0.138,39.286,92.855,2.303665e+02,2.633826e+04
human_development_index,696.0,7.133836e-01,1.366084e-01,0.354,0.630,0.735,8.000000e-01,9.570000e-01
population_age_00_09,696.0,5.825745e+06,2.045043e+07,228.000,77195.500,855419.000,4.424389e+06,2.348616e+08
population_age_10_19,696.0,5.444217e+06,2.083639e+07,216.000,74941.250,841274.000,3.971320e+06,2.522015e+08
population_age_20_29,696.0,5.166135e+06,2.067678e+07,177.000,87289.750,839990.000,3.377518e+06,2.399021e+08
population_age_30_39,696.0,4.979918e+06,2.123925e+07,145.000,88585.750,878556.000,2.993495e+06,2.288304e+08
population_age_40_49,696.0,4.198047e+06,1.853651e+07,162.000,68503.250,725142.000,2.286421e+06,2.161118e+08
population_age_50_59,696.0,3.588847e+06,1.724316e+07,138.000,51510.750,561299.000,1.591139e+06,2.221859e+08
population_age_60_69,696.0,2.541089e+06,1.190284e+07,76.000,34879.000,363824.000,1.243251e+06,1.516639e+08
population_age_70_79,696.0,1.338927e+06,5.746340e+06,28.000,16725.000,179965.000,5.952460e+05,7.149430e+07
population_age_80_and_older,696.0,6.226669e+05,2.350897e+06,11.000,5558.000,53487.000,3.038110e+05,2.661810e+07

--- בדיקת ערכים חסרים (Missing Values) בקובץ המאוחד ---

                             כמות ערכי NULL  אחוז ערכי NULL
location_key                              0        0.000000
YEAR                                      0        0.000000
country_code                              0        0.000000
country_name                              0        0.000000
aggregation_level                         0        0.000000
new_confirmed                             0        0.000000
new_deceased                              0        0.000000
new_recovered                             0        0.000000
new_tested                                0        0.000000
cumulative_confirmed                      0        0.000000
cumulative_deceased                       0        0.000000
cumulative_recovered                      0        0.000000
cumulative_tested                         0        0.000000
population                                3        0.429185
population_male                           3        0.429185
population_female                         3        0.429185
population_rural                          3        0.429185
population_urban                          3        0.429185
population_largest_city                   3        0.429185
population_clustered                      3        0.429185
population_density                        3        0.429185
human_development_index                   3        0.429185
population_age_00_09                      3        0.429185
population_age_10_19                      3        0.429185
population_age_20_29                      3        0.429185
population_age_30_39                      3        0.429185
population_age_40_49                      3        0.429185
population_age_50_59                      3        0.429185
population_age_60_69                      3        0.429185
population_age_70_79                      3        0.429185
population_age_80_and_older               3        0.429185

In [ ]:
import os
import pandas as pd

# הגדרת ה-PATH שלכן לשמירה ב-Google Drive
FOLDER_PATH = '/content/drive/MyDrive/DS_IsTheWorldReadyForTheNextPandemic/DATASET TO USE/'
OUTPUT_NAME = 'merged_epidemiology_demographics_yearly.csv'
OUTPUT_PATH = os.path.join(FOLDER_PATH, OUTPUT_NAME)

print("1. מכין את משתני הזיכרון המקוריים...")
# יצירת עותקים נקיים וניקוי רווחים נסתרים משמות העמודות
df_epi_base = df_yearly.copy()
df_epi_base.columns = df_epi_base.columns.str.strip()

df_demo_base = df_demo_cleaned.copy()
df_demo_base.columns = df_demo_base.columns.str.strip()

# =====================================================================
# 2. ניקוי עמודות כפולות מטבלת הדמוגרפיה לפני החיבור
# =====================================================================
cols_to_drop_from_demo = ['country_code', 'country_name', 'aggregation_level']
df_demo_filtered = df_demo_base.drop(columns=[col for col in cols_to_drop_from_demo if col in df_demo_base.columns])

# =====================================================================
# 3. ביצוע ה-Left Join לפי מפתח המדינה (location_key) - שמירה על כל העמודות
# =====================================================================
print("2. מבצע מיזוג שמאלי (Left Join) ושומר על כל העמודות המקוריות...")
df_epidemiology_demographics = pd.merge(
    df_epi_base,        # טבלת הבסיס השנתית האפידמיולוגית
    df_demo_filtered,   # טבלת הדמוגרפיה המסוננת
    on='location_key',  # החיבור מתבצע לפי מפתח המדינה
    how='left'          # שמירה על כל שורות התחלואה והתאמת הדמוגרפיה אליהן
)

# =====================================================================
# 4. חישוב משתנה X4 המדויק על בסיס העמודה new_tested
# =====================================================================
print("3. מחשב את משתנה X4 (סך בדיקות ל-1,000 איש) מתוך עמודת new_tested...")

# וידוא ששני השדות קיימים בטבלה המשולבת
if 'new_tested' in df_epidemiology_demographics.columns and 'population' in df_epidemiology_demographics.columns:
    # חישוב הנוסחה: (בדיקות חלקי אוכלוסייה) כפול 1,000
    df_epidemiology_demographics['X4'] = (df_epidemiology_demographics['new_tested'] / df_epidemiology_demographics['population']) * 1000

    # טיפול במצבים של חלוקה באפס (אם יש מדינה עם אוכלוסייה 0) או ערכים חסרים
    df_epidemiology_demographics['X4'] = df_epidemiology_demographics['X4'].fillna(0)
else:
    print("שגיאה: העמודות new_tested או population לא נמצאו בטבלה!")

# =====================================================================
# 5. ניקוי שלאחר המיזוג: מילוי ערכים חסרים (NaN) מבוקר (לא גורף)
# =====================================================================
# נמלא ב-0 רק עמודות של מונים אפידמיולוגיים יומיים/שנתיים
cols_to_fill_zero = ['new_confirmed', 'new_deceased', 'new_recovered', 'new_tested',
                     'cumulative_confirmed', 'cumulative_deceased', 'cumulative_recovered', 'cumulative_tested']

for col in cols_to_fill_zero:
    if col in df_epidemiology_demographics.columns:
        df_epidemiology_demographics[col] = df_epidemiology_demographics[col].fillna(0)

# עמודות המדדים, האחוזים והתמותה העודפת נשארות כפי שהן לטיפול בחציון בשלבים הבאים

# =====================================================================
# 6. שמירת הקובץ המתוקן והמלא ל-Google Drive
# =====================================================================
df_epidemiology_demographics.to_csv(OUTPUT_PATH, index=False)

print(f"\n--- הקובץ שוחזר, חושב ותוקן בהצלחה! ---")
print(f"הקובץ המלא נשמר בשם: {OUTPUT_NAME}")
print(f"מימדי הטבלה המשוחזרת (שורות, עמודות כולל X4): {df_epidemiology_demographics.shape}")

1. מכין את משתני הזיכרון המקוריים...
2. מבצע מיזוג שמאלי (Left Join) ושומר על כל העמודות המקוריות...
3. מחשב את משתנה X4 (סך בדיקות ל-1,000 איש) מתוך עמודת new_tested...

--- הקובץ שוחזר, חושב ותוקן בהצלחה! ---
הקובץ המלא נשמר בשם: merged_epidemiology_demographics_yearly.csv
מימדי הטבלה המשוחזרת (שורות, עמודות כולל X4): (699, 32)

In [ ]:
print(df_merged_4.columns.tolist())

['location_key', 'YEAR', 'country_code', 'country_name', 'aggregation_level', 'new_confirmed', 'new_deceased', 'new_recovered', 'new_tested', 'cumulative_confirmed', 'cumulative_deceased', 'cumulative_recovered', 'cumulative_tested', 'population', 'population_male', 'population_female', 'population_rural', 'population_urban', 'population_largest_city', 'population_clustered', 'population_density', 'human_development_index', 'population_age_00_09', 'population_age_10_19', 'population_age_20_29', 'population_age_30_39', 'population_age_40_49', 'population_age_50_59', 'population_age_60_69', 'population_age_70_79', 'population_age_80_and_older']